//
// Copyright Cedar Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: Messages.proto

package ffi

import (
	core "github.com/cedar-policy/cedar-spec/cedar-go-drt/internal/proto/pb/core"
	validator "github.com/cedar-policy/cedar-spec/cedar-go-drt/internal/proto/pb/validator"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtOp int32

const (
	ExtOp_DecimalVal       ExtOp = 0
	ExtOp_IPaddrIsV4       ExtOp = 1
	ExtOp_IPaddrAddrV4     ExtOp = 2
	ExtOp_IPaddrPrefixV4   ExtOp = 3
	ExtOp_IPaddrAddrV6     ExtOp = 4
	ExtOp_IPaddrPrefixV6   ExtOp = 5
	ExtOp_DatetimeVal      ExtOp = 6
	ExtOp_DatetimeOfBitVec ExtOp = 7
	ExtOp_DurationVal      ExtOp = 8
	ExtOp_DurationOfBitVec ExtOp = 9
)

// Enum value maps for ExtOp.
var (
	ExtOp_name = map[int32]string{
		0: "DecimalVal",
		1: "IPaddrIsV4",
		2: "IPaddrAddrV4",
		3: "IPaddrPrefixV4",
		4: "IPaddrAddrV6",
		5: "IPaddrPrefixV6",
		6: "DatetimeVal",
		7: "DatetimeOfBitVec",
		8: "DurationVal",
		9: "DurationOfBitVec",
	}
	ExtOp_value = map[string]int32{
		"DecimalVal":       0,
		"IPaddrIsV4":       1,
		"IPaddrAddrV4":     2,
		"IPaddrPrefixV4":   3,
		"IPaddrAddrV6":     4,
		"IPaddrPrefixV6":   5,
		"DatetimeVal":      6,
		"DatetimeOfBitVec": 7,
		"DurationVal":      8,
		"DurationOfBitVec": 9,
	}
)

func (x ExtOp) Enum() *ExtOp {
	p := new(ExtOp)
	*p = x
	return p
}

func (x ExtOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtOp) Descriptor() protoreflect.EnumDescriptor {
	return file_Messages_proto_enumTypes[0].Descriptor()
}

func (ExtOp) Type() protoreflect.EnumType {
	return &file_Messages_proto_enumTypes[0]
}

func (x ExtOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtOp.Descriptor instead.
func (ExtOp) EnumDescriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{0}
}

type ExtType int32

const (
	ExtType_IpAddrType   ExtType = 0
	ExtType_DecimalType  ExtType = 1
	ExtType_DatetimeType ExtType = 2
	ExtType_DurationType ExtType = 3
)

// Enum value maps for ExtType.
var (
	ExtType_name = map[int32]string{
		0: "IpAddrType",
		1: "DecimalType",
		2: "DatetimeType",
		3: "DurationType",
	}
	ExtType_value = map[string]int32{
		"IpAddrType":   0,
		"DecimalType":  1,
		"DatetimeType": 2,
		"DurationType": 3,
	}
)

func (x ExtType) Enum() *ExtType {
	p := new(ExtType)
	*p = x
	return p
}

func (x ExtType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtType) Descriptor() protoreflect.EnumDescriptor {
	return file_Messages_proto_enumTypes[1].Descriptor()
}

func (ExtType) Type() protoreflect.EnumType {
	return &file_Messages_proto_enumTypes[1]
}

func (x ExtType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtType.Descriptor instead.
func (ExtType) EnumDescriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{1}
}

type Op_BaseOp int32

const (
	Op_Not       Op_BaseOp = 0
	Op_And       Op_BaseOp = 1
	Op_Or        Op_BaseOp = 2
	Op_Eq        Op_BaseOp = 3
	Op_Ite       Op_BaseOp = 4
	Op_Bvneg     Op_BaseOp = 5
	Op_Bvadd     Op_BaseOp = 6
	Op_Bvsub     Op_BaseOp = 7
	Op_Bvmul     Op_BaseOp = 8
	Op_Bvsdiv    Op_BaseOp = 9
	Op_Bvudiv    Op_BaseOp = 10
	Op_Bvsrem    Op_BaseOp = 11
	Op_Bvsmod    Op_BaseOp = 12
	Op_Bvumod    Op_BaseOp = 13
	Op_Bvshl     Op_BaseOp = 14
	Op_Bvlshr    Op_BaseOp = 15
	Op_Bvslt     Op_BaseOp = 16
	Op_Bvsle     Op_BaseOp = 17
	Op_Bvult     Op_BaseOp = 18
	Op_Bvule     Op_BaseOp = 19
	Op_Bvnego    Op_BaseOp = 20
	Op_Bvsaddo   Op_BaseOp = 21
	Op_Bvssubo   Op_BaseOp = 22
	Op_Bvsmulo   Op_BaseOp = 23
	Op_SetMember Op_BaseOp = 24
	Op_SetSubset Op_BaseOp = 25
	Op_SetInter  Op_BaseOp = 26
	Op_OptionGet Op_BaseOp = 27
)

// Enum value maps for Op_BaseOp.
var (
	Op_BaseOp_name = map[int32]string{
		0:  "Not",
		1:  "And",
		2:  "Or",
		3:  "Eq",
		4:  "Ite",
		5:  "Bvneg",
		6:  "Bvadd",
		7:  "Bvsub",
		8:  "Bvmul",
		9:  "Bvsdiv",
		10: "Bvudiv",
		11: "Bvsrem",
		12: "Bvsmod",
		13: "Bvumod",
		14: "Bvshl",
		15: "Bvlshr",
		16: "Bvslt",
		17: "Bvsle",
		18: "Bvult",
		19: "Bvule",
		20: "Bvnego",
		21: "Bvsaddo",
		22: "Bvssubo",
		23: "Bvsmulo",
		24: "SetMember",
		25: "SetSubset",
		26: "SetInter",
		27: "OptionGet",
	}
	Op_BaseOp_value = map[string]int32{
		"Not":       0,
		"And":       1,
		"Or":        2,
		"Eq":        3,
		"Ite":       4,
		"Bvneg":     5,
		"Bvadd":     6,
		"Bvsub":     7,
		"Bvmul":     8,
		"Bvsdiv":    9,
		"Bvudiv":    10,
		"Bvsrem":    11,
		"Bvsmod":    12,
		"Bvumod":    13,
		"Bvshl":     14,
		"Bvlshr":    15,
		"Bvslt":     16,
		"Bvsle":     17,
		"Bvult":     18,
		"Bvule":     19,
		"Bvnego":    20,
		"Bvsaddo":   21,
		"Bvssubo":   22,
		"Bvsmulo":   23,
		"SetMember": 24,
		"SetSubset": 25,
		"SetInter":  26,
		"OptionGet": 27,
	}
)

func (x Op_BaseOp) Enum() *Op_BaseOp {
	p := new(Op_BaseOp)
	*p = x
	return p
}

func (x Op_BaseOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op_BaseOp) Descriptor() protoreflect.EnumDescriptor {
	return file_Messages_proto_enumTypes[2].Descriptor()
}

func (Op_BaseOp) Type() protoreflect.EnumType {
	return &file_Messages_proto_enumTypes[2]
}

func (x Op_BaseOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op_BaseOp.Descriptor instead.
func (Op_BaseOp) EnumDescriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{15, 0}
}

type TermPrimType_Prim int32

const (
	TermPrimType_Bool   TermPrimType_Prim = 0
	TermPrimType_String TermPrimType_Prim = 1
)

// Enum value maps for TermPrimType_Prim.
var (
	TermPrimType_Prim_name = map[int32]string{
		0: "Bool",
		1: "String",
	}
	TermPrimType_Prim_value = map[string]int32{
		"Bool":   0,
		"String": 1,
	}
)

func (x TermPrimType_Prim) Enum() *TermPrimType_Prim {
	p := new(TermPrimType_Prim)
	*p = x
	return p
}

func (x TermPrimType_Prim) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TermPrimType_Prim) Descriptor() protoreflect.EnumDescriptor {
	return file_Messages_proto_enumTypes[3].Descriptor()
}

func (TermPrimType_Prim) Type() protoreflect.EnumType {
	return &file_Messages_proto_enumTypes[3]
}

func (x TermPrimType_Prim) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TermPrimType_Prim.Descriptor instead.
func (TermPrimType_Prim) EnumDescriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{21, 0}
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *core.TemplateBody     `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Policy        *core.Policy           `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_Messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetTemplate() *core.TemplateBody {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Policy) GetPolicy() *core.Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// Authorization / Evaluation Specific Messages
type AuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *core.Request          `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Policies      *core.PolicySet        `protobuf:"bytes,2,opt,name=policies,proto3" json:"policies,omitempty"`
	Entities      *core.Entities         `protobuf:"bytes,3,opt,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_Messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationRequest) GetRequest() *core.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthorizationRequest) GetPolicies() *core.PolicySet {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *AuthorizationRequest) GetEntities() *core.Entities {
	if x != nil {
		return x.Entities
	}
	return nil
}

type EvaluationRequestChecked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *core.Expr             `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Request       *core.Request          `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Entities      *core.Entities         `protobuf:"bytes,3,opt,name=entities,proto3" json:"entities,omitempty"`
	Expected      *core.Expr             `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequestChecked) Reset() {
	*x = EvaluationRequestChecked{}
	mi := &file_Messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequestChecked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequestChecked) ProtoMessage() {}

func (x *EvaluationRequestChecked) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequestChecked.ProtoReflect.Descriptor instead.
func (*EvaluationRequestChecked) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluationRequestChecked) GetExpr() *core.Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *EvaluationRequestChecked) GetRequest() *core.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *EvaluationRequestChecked) GetEntities() *core.Entities {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EvaluationRequestChecked) GetExpected() *core.Expr {
	if x != nil {
		return x.Expected
	}
	return nil
}

// Validation Specific Messages
type EntityValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *validator.Schema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Entities      *core.Entities         `protobuf:"bytes,2,opt,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityValidationRequest) Reset() {
	*x = EntityValidationRequest{}
	mi := &file_Messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityValidationRequest) ProtoMessage() {}

func (x *EntityValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityValidationRequest.ProtoReflect.Descriptor instead.
func (*EntityValidationRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{3}
}

func (x *EntityValidationRequest) GetSchema() *validator.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *EntityValidationRequest) GetEntities() *core.Entities {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RequestValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *validator.Schema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Request       *core.Request          `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestValidationRequest) Reset() {
	*x = RequestValidationRequest{}
	mi := &file_Messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestValidationRequest) ProtoMessage() {}

func (x *RequestValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestValidationRequest.ProtoReflect.Descriptor instead.
func (*RequestValidationRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{4}
}

func (x *RequestValidationRequest) GetSchema() *validator.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *RequestValidationRequest) GetRequest() *core.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type ValidationRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Schema        *validator.Schema        `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Policies      *core.PolicySet          `protobuf:"bytes,2,opt,name=policies,proto3" json:"policies,omitempty"`
	Mode          validator.ValidationMode `protobuf:"varint,3,opt,name=mode,proto3,enum=cedar_policy_validator.ValidationMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_Messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationRequest) GetSchema() *validator.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ValidationRequest) GetPolicies() *core.PolicySet {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *ValidationRequest) GetMode() validator.ValidationMode {
	if x != nil {
		return x.Mode
	}
	return validator.ValidationMode(0)
}

type LevelValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *validator.Schema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Policies      *core.PolicySet        `protobuf:"bytes,2,opt,name=policies,proto3" json:"policies,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelValidationRequest) Reset() {
	*x = LevelValidationRequest{}
	mi := &file_Messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelValidationRequest) ProtoMessage() {}

func (x *LevelValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelValidationRequest.ProtoReflect.Descriptor instead.
func (*LevelValidationRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{6}
}

func (x *LevelValidationRequest) GetSchema() *validator.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *LevelValidationRequest) GetPolicies() *core.PolicySet {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *LevelValidationRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// SymCC Specific Messages
type RequestEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *core.Name             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Action        *core.EntityUid        `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *core.Name             `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEnv) Reset() {
	*x = RequestEnv{}
	mi := &file_Messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnv) ProtoMessage() {}

func (x *RequestEnv) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnv.ProtoReflect.Descriptor instead.
func (*RequestEnv) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{7}
}

func (x *RequestEnv) GetPrincipal() *core.Name {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *RequestEnv) GetAction() *core.EntityUid {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RequestEnv) GetResource() *core.Name {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CheckPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Request       *RequestEnv            `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPolicyRequest) Reset() {
	*x = CheckPolicyRequest{}
	mi := &file_Messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPolicyRequest) ProtoMessage() {}

func (x *CheckPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPolicyRequest.ProtoReflect.Descriptor instead.
func (*CheckPolicyRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CheckPolicyRequest) GetRequest() *RequestEnv {
	if x != nil {
		return x.Request
	}
	return nil
}

type CheckPolicySetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicySet     *core.PolicySet        `protobuf:"bytes,1,opt,name=policySet,proto3" json:"policySet,omitempty"`
	Request       *RequestEnv            `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPolicySetRequest) Reset() {
	*x = CheckPolicySetRequest{}
	mi := &file_Messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPolicySetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPolicySetRequest) ProtoMessage() {}

func (x *CheckPolicySetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPolicySetRequest.ProtoReflect.Descriptor instead.
func (*CheckPolicySetRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPolicySetRequest) GetPolicySet() *core.PolicySet {
	if x != nil {
		return x.PolicySet
	}
	return nil
}

func (x *CheckPolicySetRequest) GetRequest() *RequestEnv {
	if x != nil {
		return x.Request
	}
	return nil
}

type ComparePoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy1       *Policy                `protobuf:"bytes,1,opt,name=policy1,proto3" json:"policy1,omitempty"`
	Policy2       *Policy                `protobuf:"bytes,2,opt,name=policy2,proto3" json:"policy2,omitempty"`
	Request       *RequestEnv            `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComparePoliciesRequest) Reset() {
	*x = ComparePoliciesRequest{}
	mi := &file_Messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparePoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparePoliciesRequest) ProtoMessage() {}

func (x *ComparePoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparePoliciesRequest.ProtoReflect.Descriptor instead.
func (*ComparePoliciesRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{10}
}

func (x *ComparePoliciesRequest) GetPolicy1() *Policy {
	if x != nil {
		return x.Policy1
	}
	return nil
}

func (x *ComparePoliciesRequest) GetPolicy2() *Policy {
	if x != nil {
		return x.Policy2
	}
	return nil
}

func (x *ComparePoliciesRequest) GetRequest() *RequestEnv {
	if x != nil {
		return x.Request
	}
	return nil
}

type ComparePolicySetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPolicySet  *core.PolicySet        `protobuf:"bytes,1,opt,name=srcPolicySet,proto3" json:"srcPolicySet,omitempty"`
	TgtPolicySet  *core.PolicySet        `protobuf:"bytes,2,opt,name=tgtPolicySet,proto3" json:"tgtPolicySet,omitempty"`
	Request       *RequestEnv            `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComparePolicySetsRequest) Reset() {
	*x = ComparePolicySetsRequest{}
	mi := &file_Messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparePolicySetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparePolicySetsRequest) ProtoMessage() {}

func (x *ComparePolicySetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparePolicySetsRequest.ProtoReflect.Descriptor instead.
func (*ComparePolicySetsRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{11}
}

func (x *ComparePolicySetsRequest) GetSrcPolicySet() *core.PolicySet {
	if x != nil {
		return x.SrcPolicySet
	}
	return nil
}

func (x *ComparePolicySetsRequest) GetTgtPolicySet() *core.PolicySet {
	if x != nil {
		return x.TgtPolicySet
	}
	return nil
}

func (x *ComparePolicySetsRequest) GetRequest() *RequestEnv {
	if x != nil {
		return x.Request
	}
	return nil
}

// Term Types
type UUF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg           *TermType              `protobuf:"bytes,2,opt,name=arg,proto3" json:"arg,omitempty"`
	Out           *TermType              `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUF) Reset() {
	*x = UUF{}
	mi := &file_Messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUF) ProtoMessage() {}

func (x *UUF) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUF.ProtoReflect.Descriptor instead.
func (*UUF) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{12}
}

func (x *UUF) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UUF) GetArg() *TermType {
	if x != nil {
		return x.Arg
	}
	return nil
}

func (x *UUF) GetOut() *TermType {
	if x != nil {
		return x.Out
	}
	return nil
}

type PatElem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Elem:
	//
	//	*PatElem_Star
	//	*PatElem_Char
	Elem          isPatElem_Elem `protobuf_oneof:"elem"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatElem) Reset() {
	*x = PatElem{}
	mi := &file_Messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatElem) ProtoMessage() {}

func (x *PatElem) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatElem.ProtoReflect.Descriptor instead.
func (*PatElem) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{13}
}

func (x *PatElem) GetElem() isPatElem_Elem {
	if x != nil {
		return x.Elem
	}
	return nil
}

func (x *PatElem) GetStar() bool {
	if x != nil {
		if x, ok := x.Elem.(*PatElem_Star); ok {
			return x.Star
		}
	}
	return false
}

func (x *PatElem) GetChar() uint32 {
	if x != nil {
		if x, ok := x.Elem.(*PatElem_Char); ok {
			return x.Char
		}
	}
	return 0
}

type isPatElem_Elem interface {
	isPatElem_Elem()
}

type PatElem_Star struct {
	Star bool `protobuf:"varint,1,opt,name=star,proto3,oneof"`
}

type PatElem_Char struct {
	Char uint32 `protobuf:"varint,2,opt,name=char,proto3,oneof"`
}

func (*PatElem_Star) isPatElem_Elem() {}

func (*PatElem_Char) isPatElem_Elem() {}

type Pattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       []*PatElem             `protobuf:"bytes,1,rep,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pattern) Reset() {
	*x = Pattern{}
	mi := &file_Messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pattern) ProtoMessage() {}

func (x *Pattern) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pattern.ProtoReflect.Descriptor instead.
func (*Pattern) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{14}
}

func (x *Pattern) GetPattern() []*PatElem {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type Op struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Op_BaseOp_
	//	*Op_Uuf
	//	*Op_ZeroExtend
	//	*Op_RecordGet
	//	*Op_StringLike
	//	*Op_ExtOp
	Op            isOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_Messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{15}
}

func (x *Op) GetOp() isOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Op) GetBaseOp() Op_BaseOp {
	if x != nil {
		if x, ok := x.Op.(*Op_BaseOp_); ok {
			return x.BaseOp
		}
	}
	return Op_Not
}

func (x *Op) GetUuf() *UUF {
	if x != nil {
		if x, ok := x.Op.(*Op_Uuf); ok {
			return x.Uuf
		}
	}
	return nil
}

func (x *Op) GetZeroExtend() uint32 {
	if x != nil {
		if x, ok := x.Op.(*Op_ZeroExtend); ok {
			return x.ZeroExtend
		}
	}
	return 0
}

func (x *Op) GetRecordGet() string {
	if x != nil {
		if x, ok := x.Op.(*Op_RecordGet); ok {
			return x.RecordGet
		}
	}
	return ""
}

func (x *Op) GetStringLike() *Pattern {
	if x != nil {
		if x, ok := x.Op.(*Op_StringLike); ok {
			return x.StringLike
		}
	}
	return nil
}

func (x *Op) GetExtOp() ExtOp {
	if x != nil {
		if x, ok := x.Op.(*Op_ExtOp); ok {
			return x.ExtOp
		}
	}
	return ExtOp_DecimalVal
}

type isOp_Op interface {
	isOp_Op()
}

type Op_BaseOp_ struct {
	BaseOp Op_BaseOp `protobuf:"varint,1,opt,name=base_op,json=baseOp,proto3,enum=cedar_proto_ffi.Op_BaseOp,oneof"`
}

type Op_Uuf struct {
	Uuf *UUF `protobuf:"bytes,2,opt,name=uuf,proto3,oneof"`
}

type Op_ZeroExtend struct {
	ZeroExtend uint32 `protobuf:"varint,3,opt,name=zero_extend,json=zeroExtend,proto3,oneof"`
}

type Op_RecordGet struct {
	RecordGet string `protobuf:"bytes,4,opt,name=record_get,json=recordGet,proto3,oneof"`
}

type Op_StringLike struct {
	StringLike *Pattern `protobuf:"bytes,5,opt,name=string_like,json=stringLike,proto3,oneof"`
}

type Op_ExtOp struct {
	ExtOp ExtOp `protobuf:"varint,6,opt,name=ext_op,json=extOp,proto3,enum=cedar_proto_ffi.ExtOp,oneof"`
}

func (*Op_BaseOp_) isOp_Op() {}

func (*Op_Uuf) isOp_Op() {}

func (*Op_ZeroExtend) isOp_Op() {}

func (*Op_RecordGet) isOp_Op() {}

func (*Op_StringLike) isOp_Op() {}

func (*Op_ExtOp) isOp_Op() {}

type Bitvec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bitvec) Reset() {
	*x = Bitvec{}
	mi := &file_Messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bitvec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bitvec) ProtoMessage() {}

func (x *Bitvec) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bitvec.ProtoReflect.Descriptor instead.
func (*Bitvec) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{16}
}

func (x *Bitvec) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Bitvec) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             int64                  `protobuf:"varint,1,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_Messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{17}
}

func (x *Decimal) GetD() int64 {
	if x != nil {
		return x.D
	}
	return 0
}

type IpAddr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*IpAddr_V4
	//	*IpAddr_V6
	Version       isIpAddr_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpAddr) Reset() {
	*x = IpAddr{}
	mi := &file_Messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddr) ProtoMessage() {}

func (x *IpAddr) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddr.ProtoReflect.Descriptor instead.
func (*IpAddr) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{18}
}

func (x *IpAddr) GetVersion() isIpAddr_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *IpAddr) GetV4() *IpAddr_Cidr {
	if x != nil {
		if x, ok := x.Version.(*IpAddr_V4); ok {
			return x.V4
		}
	}
	return nil
}

func (x *IpAddr) GetV6() *IpAddr_Cidr {
	if x != nil {
		if x, ok := x.Version.(*IpAddr_V6); ok {
			return x.V6
		}
	}
	return nil
}

type isIpAddr_Version interface {
	isIpAddr_Version()
}

type IpAddr_V4 struct {
	V4 *IpAddr_Cidr `protobuf:"bytes,1,opt,name=v4,proto3,oneof"`
}

type IpAddr_V6 struct {
	V6 *IpAddr_Cidr `protobuf:"bytes,2,opt,name=v6,proto3,oneof"`
}

func (*IpAddr_V4) isIpAddr_Version() {}

func (*IpAddr_V6) isIpAddr_Version() {}

type Datetime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datetime) Reset() {
	*x = Datetime{}
	mi := &file_Messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datetime) ProtoMessage() {}

func (x *Datetime) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datetime.ProtoReflect.Descriptor instead.
func (*Datetime) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{19}
}

func (x *Datetime) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_Messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{20}
}

func (x *Duration) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type TermPrimType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PrimType:
	//
	//	*TermPrimType_Prim_
	//	*TermPrimType_Bitvec
	//	*TermPrimType_Entity
	//	*TermPrimType_Ext
	PrimType      isTermPrimType_PrimType `protobuf_oneof:"prim_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermPrimType) Reset() {
	*x = TermPrimType{}
	mi := &file_Messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermPrimType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermPrimType) ProtoMessage() {}

func (x *TermPrimType) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermPrimType.ProtoReflect.Descriptor instead.
func (*TermPrimType) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{21}
}

func (x *TermPrimType) GetPrimType() isTermPrimType_PrimType {
	if x != nil {
		return x.PrimType
	}
	return nil
}

func (x *TermPrimType) GetPrim() TermPrimType_Prim {
	if x != nil {
		if x, ok := x.PrimType.(*TermPrimType_Prim_); ok {
			return x.Prim
		}
	}
	return TermPrimType_Bool
}

func (x *TermPrimType) GetBitvec() uint32 {
	if x != nil {
		if x, ok := x.PrimType.(*TermPrimType_Bitvec); ok {
			return x.Bitvec
		}
	}
	return 0
}

func (x *TermPrimType) GetEntity() *core.Name {
	if x != nil {
		if x, ok := x.PrimType.(*TermPrimType_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *TermPrimType) GetExt() ExtType {
	if x != nil {
		if x, ok := x.PrimType.(*TermPrimType_Ext); ok {
			return x.Ext
		}
	}
	return ExtType_IpAddrType
}

type isTermPrimType_PrimType interface {
	isTermPrimType_PrimType()
}

type TermPrimType_Prim_ struct {
	Prim TermPrimType_Prim `protobuf:"varint,1,opt,name=prim,proto3,enum=cedar_proto_ffi.TermPrimType_Prim,oneof"`
}

type TermPrimType_Bitvec struct {
	Bitvec uint32 `protobuf:"varint,2,opt,name=bitvec,proto3,oneof"`
}

type TermPrimType_Entity struct {
	Entity *core.Name `protobuf:"bytes,3,opt,name=entity,proto3,oneof"`
}

type TermPrimType_Ext struct {
	Ext ExtType `protobuf:"varint,4,opt,name=ext,proto3,enum=cedar_proto_ffi.ExtType,oneof"`
}

func (*TermPrimType_Prim_) isTermPrimType_PrimType() {}

func (*TermPrimType_Bitvec) isTermPrimType_PrimType() {}

func (*TermPrimType_Entity) isTermPrimType_PrimType() {}

func (*TermPrimType_Ext) isTermPrimType_PrimType() {}

type TermType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TermType:
	//
	//	*TermType_Prim
	//	*TermType_Option
	//	*TermType_Set
	//	*TermType_Record
	TermType      isTermType_TermType `protobuf_oneof:"term_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermType) Reset() {
	*x = TermType{}
	mi := &file_Messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermType) ProtoMessage() {}

func (x *TermType) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermType.ProtoReflect.Descriptor instead.
func (*TermType) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{22}
}

func (x *TermType) GetTermType() isTermType_TermType {
	if x != nil {
		return x.TermType
	}
	return nil
}

func (x *TermType) GetPrim() *TermPrimType {
	if x != nil {
		if x, ok := x.TermType.(*TermType_Prim); ok {
			return x.Prim
		}
	}
	return nil
}

func (x *TermType) GetOption() *TermType {
	if x != nil {
		if x, ok := x.TermType.(*TermType_Option); ok {
			return x.Option
		}
	}
	return nil
}

func (x *TermType) GetSet() *TermType {
	if x != nil {
		if x, ok := x.TermType.(*TermType_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *TermType) GetRecord() *TermType_RecordType {
	if x != nil {
		if x, ok := x.TermType.(*TermType_Record); ok {
			return x.Record
		}
	}
	return nil
}

type isTermType_TermType interface {
	isTermType_TermType()
}

type TermType_Prim struct {
	Prim *TermPrimType `protobuf:"bytes,1,opt,name=prim,proto3,oneof"`
}

type TermType_Option struct {
	Option *TermType `protobuf:"bytes,2,opt,name=option,proto3,oneof"`
}

type TermType_Set struct {
	Set *TermType `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

type TermType_Record struct {
	Record *TermType_RecordType `protobuf:"bytes,4,opt,name=record,proto3,oneof"`
}

func (*TermType_Prim) isTermType_TermType() {}

func (*TermType_Option) isTermType_TermType() {}

func (*TermType_Set) isTermType_TermType() {}

func (*TermType_Record) isTermType_TermType() {}

type TermVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ty            *TermType              `protobuf:"bytes,2,opt,name=ty,proto3" json:"ty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermVar) Reset() {
	*x = TermVar{}
	mi := &file_Messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermVar) ProtoMessage() {}

func (x *TermVar) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermVar.ProtoReflect.Descriptor instead.
func (*TermVar) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{23}
}

func (x *TermVar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TermVar) GetTy() *TermType {
	if x != nil {
		return x.Ty
	}
	return nil
}

type Ext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ext:
	//
	//	*Ext_Decimal
	//	*Ext_Ipaddr
	//	*Ext_Datetime
	//	*Ext_Duration
	Ext           isExt_Ext `protobuf_oneof:"ext"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ext) Reset() {
	*x = Ext{}
	mi := &file_Messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ext) ProtoMessage() {}

func (x *Ext) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ext.ProtoReflect.Descriptor instead.
func (*Ext) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{24}
}

func (x *Ext) GetExt() isExt_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *Ext) GetDecimal() *Decimal {
	if x != nil {
		if x, ok := x.Ext.(*Ext_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *Ext) GetIpaddr() *IpAddr {
	if x != nil {
		if x, ok := x.Ext.(*Ext_Ipaddr); ok {
			return x.Ipaddr
		}
	}
	return nil
}

func (x *Ext) GetDatetime() *Datetime {
	if x != nil {
		if x, ok := x.Ext.(*Ext_Datetime); ok {
			return x.Datetime
		}
	}
	return nil
}

func (x *Ext) GetDuration() *Duration {
	if x != nil {
		if x, ok := x.Ext.(*Ext_Duration); ok {
			return x.Duration
		}
	}
	return nil
}

type isExt_Ext interface {
	isExt_Ext()
}

type Ext_Decimal struct {
	Decimal *Decimal `protobuf:"bytes,1,opt,name=decimal,proto3,oneof"`
}

type Ext_Ipaddr struct {
	Ipaddr *IpAddr `protobuf:"bytes,2,opt,name=ipaddr,proto3,oneof"`
}

type Ext_Datetime struct {
	Datetime *Datetime `protobuf:"bytes,3,opt,name=datetime,proto3,oneof"`
}

type Ext_Duration struct {
	Duration *Duration `protobuf:"bytes,4,opt,name=duration,proto3,oneof"`
}

func (*Ext_Decimal) isExt_Ext() {}

func (*Ext_Ipaddr) isExt_Ext() {}

func (*Ext_Datetime) isExt_Ext() {}

func (*Ext_Duration) isExt_Ext() {}

type TermPrim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Prim:
	//
	//	*TermPrim_Bool
	//	*TermPrim_Bitvec
	//	*TermPrim_String_
	//	*TermPrim_Entity
	//	*TermPrim_Ext
	Prim          isTermPrim_Prim `protobuf_oneof:"prim"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermPrim) Reset() {
	*x = TermPrim{}
	mi := &file_Messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermPrim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermPrim) ProtoMessage() {}

func (x *TermPrim) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermPrim.ProtoReflect.Descriptor instead.
func (*TermPrim) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{25}
}

func (x *TermPrim) GetPrim() isTermPrim_Prim {
	if x != nil {
		return x.Prim
	}
	return nil
}

func (x *TermPrim) GetBool() bool {
	if x != nil {
		if x, ok := x.Prim.(*TermPrim_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *TermPrim) GetBitvec() *Bitvec {
	if x != nil {
		if x, ok := x.Prim.(*TermPrim_Bitvec); ok {
			return x.Bitvec
		}
	}
	return nil
}

func (x *TermPrim) GetString_() string {
	if x != nil {
		if x, ok := x.Prim.(*TermPrim_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *TermPrim) GetEntity() *core.EntityUid {
	if x != nil {
		if x, ok := x.Prim.(*TermPrim_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *TermPrim) GetExt() *Ext {
	if x != nil {
		if x, ok := x.Prim.(*TermPrim_Ext); ok {
			return x.Ext
		}
	}
	return nil
}

type isTermPrim_Prim interface {
	isTermPrim_Prim()
}

type TermPrim_Bool struct {
	Bool bool `protobuf:"varint,1,opt,name=bool,proto3,oneof"`
}

type TermPrim_Bitvec struct {
	Bitvec *Bitvec `protobuf:"bytes,2,opt,name=bitvec,proto3,oneof"`
}

type TermPrim_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=string,proto3,oneof"`
}

type TermPrim_Entity struct {
	Entity *core.EntityUid `protobuf:"bytes,4,opt,name=entity,proto3,oneof"`
}

type TermPrim_Ext struct {
	Ext *Ext `protobuf:"bytes,5,opt,name=ext,proto3,oneof"`
}

func (*TermPrim_Bool) isTermPrim_Prim() {}

func (*TermPrim_Bitvec) isTermPrim_Prim() {}

func (*TermPrim_String_) isTermPrim_Prim() {}

func (*TermPrim_Entity) isTermPrim_Prim() {}

func (*TermPrim_Ext) isTermPrim_Prim() {}

type Term struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Term:
	//
	//	*Term_Prim
	//	*Term_Var
	//	*Term_None
	//	*Term_Some
	//	*Term_Set_
	//	*Term_Record_
	//	*Term_App_
	Term          isTerm_Term `protobuf_oneof:"term"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Term) Reset() {
	*x = Term{}
	mi := &file_Messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Term) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term) ProtoMessage() {}

func (x *Term) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term.ProtoReflect.Descriptor instead.
func (*Term) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{26}
}

func (x *Term) GetTerm() isTerm_Term {
	if x != nil {
		return x.Term
	}
	return nil
}

func (x *Term) GetPrim() *TermPrim {
	if x != nil {
		if x, ok := x.Term.(*Term_Prim); ok {
			return x.Prim
		}
	}
	return nil
}

func (x *Term) GetVar() *TermVar {
	if x != nil {
		if x, ok := x.Term.(*Term_Var); ok {
			return x.Var
		}
	}
	return nil
}

func (x *Term) GetNone() *TermType {
	if x != nil {
		if x, ok := x.Term.(*Term_None); ok {
			return x.None
		}
	}
	return nil
}

func (x *Term) GetSome() *Term {
	if x != nil {
		if x, ok := x.Term.(*Term_Some); ok {
			return x.Some
		}
	}
	return nil
}

func (x *Term) GetSet() *Term_Set {
	if x != nil {
		if x, ok := x.Term.(*Term_Set_); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Term) GetRecord() *Term_Record {
	if x != nil {
		if x, ok := x.Term.(*Term_Record_); ok {
			return x.Record
		}
	}
	return nil
}

func (x *Term) GetApp() *Term_App {
	if x != nil {
		if x, ok := x.Term.(*Term_App_); ok {
			return x.App
		}
	}
	return nil
}

type isTerm_Term interface {
	isTerm_Term()
}

type Term_Prim struct {
	Prim *TermPrim `protobuf:"bytes,1,opt,name=prim,proto3,oneof"`
}

type Term_Var struct {
	Var *TermVar `protobuf:"bytes,2,opt,name=var,proto3,oneof"`
}

type Term_None struct {
	None *TermType `protobuf:"bytes,3,opt,name=none,proto3,oneof"`
}

type Term_Some struct {
	Some *Term `protobuf:"bytes,4,opt,name=some,proto3,oneof"`
}

type Term_Set_ struct {
	Set *Term_Set `protobuf:"bytes,5,opt,name=set,proto3,oneof"`
}

type Term_Record_ struct {
	Record *Term_Record `protobuf:"bytes,6,opt,name=record,proto3,oneof"`
}

type Term_App_ struct {
	App *Term_App `protobuf:"bytes,7,opt,name=app,proto3,oneof"`
}

func (*Term_Prim) isTerm_Term() {}

func (*Term_Var) isTerm_Term() {}

func (*Term_None) isTerm_Term() {}

func (*Term_Some) isTerm_Term() {}

func (*Term_Set_) isTerm_Term() {}

func (*Term_Record_) isTerm_Term() {}

func (*Term_App_) isTerm_Term() {}

type Asserts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asserts       []*Term                `protobuf:"bytes,1,rep,name=asserts,proto3" json:"asserts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asserts) Reset() {
	*x = Asserts{}
	mi := &file_Messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asserts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asserts) ProtoMessage() {}

func (x *Asserts) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asserts.ProtoReflect.Descriptor instead.
func (*Asserts) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{27}
}

func (x *Asserts) GetAsserts() []*Term {
	if x != nil {
		return x.Asserts
	}
	return nil
}

type CheckAssertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asserts       *Asserts               `protobuf:"bytes,1,opt,name=asserts,proto3" json:"asserts,omitempty"`
	Request       *RequestEnv            `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAssertsRequest) Reset() {
	*x = CheckAssertsRequest{}
	mi := &file_Messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAssertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAssertsRequest) ProtoMessage() {}

func (x *CheckAssertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAssertsRequest.ProtoReflect.Descriptor instead.
func (*CheckAssertsRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{28}
}

func (x *CheckAssertsRequest) GetAsserts() *Asserts {
	if x != nil {
		return x.Asserts
	}
	return nil
}

func (x *CheckAssertsRequest) GetRequest() *RequestEnv {
	if x != nil {
		return x.Request
	}
	return nil
}

// Batched evaluation request
type BatchedEvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      *core.PolicySet        `protobuf:"bytes,1,opt,name=policies,proto3" json:"policies,omitempty"`
	Schema        *validator.Schema      `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Request       *core.Request          `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Entities      *core.Entities         `protobuf:"bytes,4,opt,name=entities,proto3" json:"entities,omitempty"`
	Iteration     uint32                 `protobuf:"varint,5,opt,name=iteration,proto3" json:"iteration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedEvaluationRequest) Reset() {
	*x = BatchedEvaluationRequest{}
	mi := &file_Messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedEvaluationRequest) ProtoMessage() {}

func (x *BatchedEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedEvaluationRequest.ProtoReflect.Descriptor instead.
func (*BatchedEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{29}
}

func (x *BatchedEvaluationRequest) GetPolicies() *core.PolicySet {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *BatchedEvaluationRequest) GetSchema() *validator.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *BatchedEvaluationRequest) GetRequest() *core.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *BatchedEvaluationRequest) GetEntities() *core.Entities {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *BatchedEvaluationRequest) GetIteration() uint32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

type IpAddr_Cidr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Addr  *Bitvec                `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// Optional parameter
	Pre           *Bitvec `protobuf:"bytes,2,opt,name=pre,proto3" json:"pre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpAddr_Cidr) Reset() {
	*x = IpAddr_Cidr{}
	mi := &file_Messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddr_Cidr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddr_Cidr) ProtoMessage() {}

func (x *IpAddr_Cidr) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddr_Cidr.ProtoReflect.Descriptor instead.
func (*IpAddr_Cidr) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{18, 0}
}

func (x *IpAddr_Cidr) GetAddr() *Bitvec {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *IpAddr_Cidr) GetPre() *Bitvec {
	if x != nil {
		return x.Pre
	}
	return nil
}

type TermType_RecordField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          string                 `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Ty            *TermType              `protobuf:"bytes,2,opt,name=ty,proto3" json:"ty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermType_RecordField) Reset() {
	*x = TermType_RecordField{}
	mi := &file_Messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermType_RecordField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermType_RecordField) ProtoMessage() {}

func (x *TermType_RecordField) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermType_RecordField.ProtoReflect.Descriptor instead.
func (*TermType_RecordField) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{22, 0}
}

func (x *TermType_RecordField) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *TermType_RecordField) GetTy() *TermType {
	if x != nil {
		return x.Ty
	}
	return nil
}

type TermType_RecordType struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Fields        []*TermType_RecordField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermType_RecordType) Reset() {
	*x = TermType_RecordType{}
	mi := &file_Messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermType_RecordType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermType_RecordType) ProtoMessage() {}

func (x *TermType_RecordType) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermType_RecordType.ProtoReflect.Descriptor instead.
func (*TermType_RecordType) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{22, 1}
}

func (x *TermType_RecordType) GetFields() []*TermType_RecordField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Term_Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elts          []*Term                `protobuf:"bytes,1,rep,name=elts,proto3" json:"elts,omitempty"`
	EltTy         *TermType              `protobuf:"bytes,2,opt,name=elt_ty,json=eltTy,proto3" json:"elt_ty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Term_Set) Reset() {
	*x = Term_Set{}
	mi := &file_Messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Term_Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term_Set) ProtoMessage() {}

func (x *Term_Set) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term_Set.ProtoReflect.Descriptor instead.
func (*Term_Set) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{26, 0}
}

func (x *Term_Set) GetElts() []*Term {
	if x != nil {
		return x.Elts
	}
	return nil
}

func (x *Term_Set) GetEltTy() *TermType {
	if x != nil {
		return x.EltTy
	}
	return nil
}

type Term_RecordField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          string                 `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Term          *Term                  `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Term_RecordField) Reset() {
	*x = Term_RecordField{}
	mi := &file_Messages_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Term_RecordField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term_RecordField) ProtoMessage() {}

func (x *Term_RecordField) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term_RecordField.ProtoReflect.Descriptor instead.
func (*Term_RecordField) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{26, 1}
}

func (x *Term_RecordField) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *Term_RecordField) GetTerm() *Term {
	if x != nil {
		return x.Term
	}
	return nil
}

type Term_Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Term_RecordField    `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Term_Record) Reset() {
	*x = Term_Record{}
	mi := &file_Messages_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Term_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term_Record) ProtoMessage() {}

func (x *Term_Record) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term_Record.ProtoReflect.Descriptor instead.
func (*Term_Record) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{26, 2}
}

func (x *Term_Record) GetFields() []*Term_RecordField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Term_App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            *Op                    `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Args          []*Term                `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	RetTy         *TermType              `protobuf:"bytes,3,opt,name=ret_ty,json=retTy,proto3" json:"ret_ty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Term_App) Reset() {
	*x = Term_App{}
	mi := &file_Messages_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Term_App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term_App) ProtoMessage() {}

func (x *Term_App) ProtoReflect() protoreflect.Message {
	mi := &file_Messages_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term_App.ProtoReflect.Descriptor instead.
func (*Term_App) Descriptor() ([]byte, []int) {
	return file_Messages_proto_rawDescGZIP(), []int{26, 3}
}

func (x *Term_App) GetOp() *Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Term_App) GetArgs() []*Term {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Term_App) GetRetTy() *TermType {
	if x != nil {
		return x.RetTy
	}
	return nil
}

var File_Messages_proto protoreflect.FileDescriptor

const file_Messages_proto_rawDesc = "" +
	"\n" +
	"\x0eMessages.proto\x12\x0fcedar_proto_ffi\x1a\n" +
	"core.proto\x1a\x0fvalidator.proto\"x\n" +
	"\x06Policy\x12;\n" +
	"\btemplate\x18\x01 \x01(\v2\x1f.cedar_policy_core.TemplateBodyR\btemplate\x121\n" +
	"\x06policy\x18\x02 \x01(\v2\x19.cedar_policy_core.PolicyR\x06policy\"\xbf\x01\n" +
	"\x14AuthorizationRequest\x124\n" +
	"\arequest\x18\x01 \x01(\v2\x1a.cedar_policy_core.RequestR\arequest\x128\n" +
	"\bpolicies\x18\x02 \x01(\v2\x1c.cedar_policy_core.PolicySetR\bpolicies\x127\n" +
	"\bentities\x18\x03 \x01(\v2\x1b.cedar_policy_core.EntitiesR\bentities\"\xeb\x01\n" +
	"\x18EvaluationRequestChecked\x12+\n" +
	"\x04expr\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04expr\x124\n" +
	"\arequest\x18\x02 \x01(\v2\x1a.cedar_policy_core.RequestR\arequest\x127\n" +
	"\bentities\x18\x03 \x01(\v2\x1b.cedar_policy_core.EntitiesR\bentities\x123\n" +
	"\bexpected\x18\x04 \x01(\v2\x17.cedar_policy_core.ExprR\bexpected\"\x8a\x01\n" +
	"\x17EntityValidationRequest\x126\n" +
	"\x06schema\x18\x01 \x01(\v2\x1e.cedar_policy_validator.SchemaR\x06schema\x127\n" +
	"\bentities\x18\x02 \x01(\v2\x1b.cedar_policy_core.EntitiesR\bentities\"\x88\x01\n" +
	"\x18RequestValidationRequest\x126\n" +
	"\x06schema\x18\x01 \x01(\v2\x1e.cedar_policy_validator.SchemaR\x06schema\x124\n" +
	"\arequest\x18\x02 \x01(\v2\x1a.cedar_policy_core.RequestR\arequest\"\xc1\x01\n" +
	"\x11ValidationRequest\x126\n" +
	"\x06schema\x18\x01 \x01(\v2\x1e.cedar_policy_validator.SchemaR\x06schema\x128\n" +
	"\bpolicies\x18\x02 \x01(\v2\x1c.cedar_policy_core.PolicySetR\bpolicies\x12:\n" +
	"\x04mode\x18\x03 \x01(\x0e2&.cedar_policy_validator.ValidationModeR\x04mode\"\xa0\x01\n" +
	"\x16LevelValidationRequest\x126\n" +
	"\x06schema\x18\x01 \x01(\v2\x1e.cedar_policy_validator.SchemaR\x06schema\x128\n" +
	"\bpolicies\x18\x02 \x01(\v2\x1c.cedar_policy_core.PolicySetR\bpolicies\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"\xae\x01\n" +
	"\n" +
	"RequestEnv\x125\n" +
	"\tprincipal\x18\x01 \x01(\v2\x17.cedar_policy_core.NameR\tprincipal\x124\n" +
	"\x06action\x18\x02 \x01(\v2\x1c.cedar_policy_core.EntityUidR\x06action\x123\n" +
	"\bresource\x18\x03 \x01(\v2\x17.cedar_policy_core.NameR\bresource\"|\n" +
	"\x12CheckPolicyRequest\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.cedar_proto_ffi.PolicyR\x06policy\x125\n" +
	"\arequest\x18\x03 \x01(\v2\x1b.cedar_proto_ffi.RequestEnvR\arequest\"\x8a\x01\n" +
	"\x15CheckPolicySetRequest\x12:\n" +
	"\tpolicySet\x18\x01 \x01(\v2\x1c.cedar_policy_core.PolicySetR\tpolicySet\x125\n" +
	"\arequest\x18\x03 \x01(\v2\x1b.cedar_proto_ffi.RequestEnvR\arequest\"\xb5\x01\n" +
	"\x16ComparePoliciesRequest\x121\n" +
	"\apolicy1\x18\x01 \x01(\v2\x17.cedar_proto_ffi.PolicyR\apolicy1\x121\n" +
	"\apolicy2\x18\x02 \x01(\v2\x17.cedar_proto_ffi.PolicyR\apolicy2\x125\n" +
	"\arequest\x18\x03 \x01(\v2\x1b.cedar_proto_ffi.RequestEnvR\arequest\"\xd5\x01\n" +
	"\x18ComparePolicySetsRequest\x12@\n" +
	"\fsrcPolicySet\x18\x01 \x01(\v2\x1c.cedar_policy_core.PolicySetR\fsrcPolicySet\x12@\n" +
	"\ftgtPolicySet\x18\x02 \x01(\v2\x1c.cedar_policy_core.PolicySetR\ftgtPolicySet\x125\n" +
	"\arequest\x18\x04 \x01(\v2\x1b.cedar_proto_ffi.RequestEnvR\arequest\"o\n" +
	"\x03UUF\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x03arg\x18\x02 \x01(\v2\x19.cedar_proto_ffi.TermTypeR\x03arg\x12+\n" +
	"\x03out\x18\x03 \x01(\v2\x19.cedar_proto_ffi.TermTypeR\x03out\"=\n" +
	"\aPatElem\x12\x14\n" +
	"\x04star\x18\x01 \x01(\bH\x00R\x04star\x12\x14\n" +
	"\x04char\x18\x02 \x01(\rH\x00R\x04charB\x06\n" +
	"\x04elem\"=\n" +
	"\aPattern\x122\n" +
	"\apattern\x18\x01 \x03(\v2\x18.cedar_proto_ffi.PatElemR\apattern\"\xec\x04\n" +
	"\x02Op\x125\n" +
	"\abase_op\x18\x01 \x01(\x0e2\x1a.cedar_proto_ffi.Op.BaseOpH\x00R\x06baseOp\x12(\n" +
	"\x03uuf\x18\x02 \x01(\v2\x14.cedar_proto_ffi.UUFH\x00R\x03uuf\x12!\n" +
	"\vzero_extend\x18\x03 \x01(\rH\x00R\n" +
	"zeroExtend\x12\x1f\n" +
	"\n" +
	"record_get\x18\x04 \x01(\tH\x00R\trecordGet\x12;\n" +
	"\vstring_like\x18\x05 \x01(\v2\x18.cedar_proto_ffi.PatternH\x00R\n" +
	"stringLike\x12/\n" +
	"\x06ext_op\x18\x06 \x01(\x0e2\x16.cedar_proto_ffi.ExtOpH\x00R\x05extOp\"\xcc\x02\n" +
	"\x06BaseOp\x12\a\n" +
	"\x03Not\x10\x00\x12\a\n" +
	"\x03And\x10\x01\x12\x06\n" +
	"\x02Or\x10\x02\x12\x06\n" +
	"\x02Eq\x10\x03\x12\a\n" +
	"\x03Ite\x10\x04\x12\t\n" +
	"\x05Bvneg\x10\x05\x12\t\n" +
	"\x05Bvadd\x10\x06\x12\t\n" +
	"\x05Bvsub\x10\a\x12\t\n" +
	"\x05Bvmul\x10\b\x12\n" +
	"\n" +
	"\x06Bvsdiv\x10\t\x12\n" +
	"\n" +
	"\x06Bvudiv\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06Bvsrem\x10\v\x12\n" +
	"\n" +
	"\x06Bvsmod\x10\f\x12\n" +
	"\n" +
	"\x06Bvumod\x10\r\x12\t\n" +
	"\x05Bvshl\x10\x0e\x12\n" +
	"\n" +
	"\x06Bvlshr\x10\x0f\x12\t\n" +
	"\x05Bvslt\x10\x10\x12\t\n" +
	"\x05Bvsle\x10\x11\x12\t\n" +
	"\x05Bvult\x10\x12\x12\t\n" +
	"\x05Bvule\x10\x13\x12\n" +
	"\n" +
	"\x06Bvnego\x10\x14\x12\v\n" +
	"\aBvsaddo\x10\x15\x12\v\n" +
	"\aBvssubo\x10\x16\x12\v\n" +
	"\aBvsmulo\x10\x17\x12\r\n" +
	"\tSetMember\x10\x18\x12\r\n" +
	"\tSetSubset\x10\x19\x12\f\n" +
	"\bSetInter\x10\x1a\x12\r\n" +
	"\tOptionGet\x10\x1bB\x04\n" +
	"\x02op\"0\n" +
	"\x06Bitvec\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"\x17\n" +
	"\aDecimal\x12\f\n" +
	"\x01d\x18\x01 \x01(\x03R\x01d\"\xd3\x01\n" +
	"\x06IpAddr\x12.\n" +
	"\x02v4\x18\x01 \x01(\v2\x1c.cedar_proto_ffi.IpAddr.CidrH\x00R\x02v4\x12.\n" +
	"\x02v6\x18\x02 \x01(\v2\x1c.cedar_proto_ffi.IpAddr.CidrH\x00R\x02v6\x1a^\n" +
	"\x04Cidr\x12+\n" +
	"\x04addr\x18\x01 \x01(\v2\x17.cedar_proto_ffi.BitvecR\x04addr\x12)\n" +
	"\x03pre\x18\x02 \x01(\v2\x17.cedar_proto_ffi.BitvecR\x03preB\t\n" +
	"\aversion\"\x1c\n" +
	"\bDatetime\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x03R\x03val\"\x1c\n" +
	"\bDuration\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x03R\x03val\"\xee\x01\n" +
	"\fTermPrimType\x128\n" +
	"\x04prim\x18\x01 \x01(\x0e2\".cedar_proto_ffi.TermPrimType.PrimH\x00R\x04prim\x12\x18\n" +
	"\x06bitvec\x18\x02 \x01(\rH\x00R\x06bitvec\x121\n" +
	"\x06entity\x18\x03 \x01(\v2\x17.cedar_policy_core.NameH\x00R\x06entity\x12,\n" +
	"\x03ext\x18\x04 \x01(\x0e2\x18.cedar_proto_ffi.ExtTypeH\x00R\x03ext\"\x1c\n" +
	"\x04Prim\x12\b\n" +
	"\x04Bool\x10\x00\x12\n" +
	"\n" +
	"\x06String\x10\x01B\v\n" +
	"\tprim_type\"\x8b\x03\n" +
	"\bTermType\x123\n" +
	"\x04prim\x18\x01 \x01(\v2\x1d.cedar_proto_ffi.TermPrimTypeH\x00R\x04prim\x123\n" +
	"\x06option\x18\x02 \x01(\v2\x19.cedar_proto_ffi.TermTypeH\x00R\x06option\x12-\n" +
	"\x03set\x18\x03 \x01(\v2\x19.cedar_proto_ffi.TermTypeH\x00R\x03set\x12>\n" +
	"\x06record\x18\x04 \x01(\v2$.cedar_proto_ffi.TermType.RecordTypeH\x00R\x06record\x1aL\n" +
	"\vRecordField\x12\x12\n" +
	"\x04attr\x18\x01 \x01(\tR\x04attr\x12)\n" +
	"\x02ty\x18\x02 \x01(\v2\x19.cedar_proto_ffi.TermTypeR\x02ty\x1aK\n" +
	"\n" +
	"RecordType\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.cedar_proto_ffi.TermType.RecordFieldR\x06fieldsB\v\n" +
	"\tterm_type\"D\n" +
	"\aTermVar\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x02ty\x18\x02 \x01(\v2\x19.cedar_proto_ffi.TermTypeR\x02ty\"\xe7\x01\n" +
	"\x03Ext\x124\n" +
	"\adecimal\x18\x01 \x01(\v2\x18.cedar_proto_ffi.DecimalH\x00R\adecimal\x121\n" +
	"\x06ipaddr\x18\x02 \x01(\v2\x17.cedar_proto_ffi.IpAddrH\x00R\x06ipaddr\x127\n" +
	"\bdatetime\x18\x03 \x01(\v2\x19.cedar_proto_ffi.DatetimeH\x00R\bdatetime\x127\n" +
	"\bduration\x18\x04 \x01(\v2\x19.cedar_proto_ffi.DurationH\x00R\bdurationB\x05\n" +
	"\x03ext\"\xd7\x01\n" +
	"\bTermPrim\x12\x14\n" +
	"\x04bool\x18\x01 \x01(\bH\x00R\x04bool\x121\n" +
	"\x06bitvec\x18\x02 \x01(\v2\x17.cedar_proto_ffi.BitvecH\x00R\x06bitvec\x12\x18\n" +
	"\x06string\x18\x03 \x01(\tH\x00R\x06string\x126\n" +
	"\x06entity\x18\x04 \x01(\v2\x1c.cedar_policy_core.EntityUidH\x00R\x06entity\x12(\n" +
	"\x03ext\x18\x05 \x01(\v2\x14.cedar_proto_ffi.ExtH\x00R\x03extB\x06\n" +
	"\x04prim\"\xe2\x05\n" +
	"\x04Term\x12/\n" +
	"\x04prim\x18\x01 \x01(\v2\x19.cedar_proto_ffi.TermPrimH\x00R\x04prim\x12,\n" +
	"\x03var\x18\x02 \x01(\v2\x18.cedar_proto_ffi.TermVarH\x00R\x03var\x12/\n" +
	"\x04none\x18\x03 \x01(\v2\x19.cedar_proto_ffi.TermTypeH\x00R\x04none\x12+\n" +
	"\x04some\x18\x04 \x01(\v2\x15.cedar_proto_ffi.TermH\x00R\x04some\x12-\n" +
	"\x03set\x18\x05 \x01(\v2\x19.cedar_proto_ffi.Term.SetH\x00R\x03set\x126\n" +
	"\x06record\x18\x06 \x01(\v2\x1c.cedar_proto_ffi.Term.RecordH\x00R\x06record\x12-\n" +
	"\x03app\x18\a \x01(\v2\x19.cedar_proto_ffi.Term.AppH\x00R\x03app\x1ab\n" +
	"\x03Set\x12)\n" +
	"\x04elts\x18\x01 \x03(\v2\x15.cedar_proto_ffi.TermR\x04elts\x120\n" +
	"\x06elt_ty\x18\x02 \x01(\v2\x19.cedar_proto_ffi.TermTypeR\x05eltTy\x1aL\n" +
	"\vRecordField\x12\x12\n" +
	"\x04attr\x18\x01 \x01(\tR\x04attr\x12)\n" +
	"\x04term\x18\x02 \x01(\v2\x15.cedar_proto_ffi.TermR\x04term\x1aC\n" +
	"\x06Record\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.cedar_proto_ffi.Term.RecordFieldR\x06fields\x1a\x87\x01\n" +
	"\x03App\x12#\n" +
	"\x02op\x18\x01 \x01(\v2\x13.cedar_proto_ffi.OpR\x02op\x12)\n" +
	"\x04args\x18\x02 \x03(\v2\x15.cedar_proto_ffi.TermR\x04args\x120\n" +
	"\x06ret_ty\x18\x03 \x01(\v2\x19.cedar_proto_ffi.TermTypeR\x05retTyB\x06\n" +
	"\x04term\":\n" +
	"\aAsserts\x12/\n" +
	"\aasserts\x18\x01 \x03(\v2\x15.cedar_proto_ffi.TermR\aasserts\"\x80\x01\n" +
	"\x13CheckAssertsRequest\x122\n" +
	"\aasserts\x18\x01 \x01(\v2\x18.cedar_proto_ffi.AssertsR\aasserts\x125\n" +
	"\arequest\x18\x03 \x01(\v2\x1b.cedar_proto_ffi.RequestEnvR\arequest\"\x99\x02\n" +
	"\x18BatchedEvaluationRequest\x128\n" +
	"\bpolicies\x18\x01 \x01(\v2\x1c.cedar_policy_core.PolicySetR\bpolicies\x126\n" +
	"\x06schema\x18\x02 \x01(\v2\x1e.cedar_policy_validator.SchemaR\x06schema\x124\n" +
	"\arequest\x18\x03 \x01(\v2\x1a.cedar_policy_core.RequestR\arequest\x127\n" +
	"\bentities\x18\x04 \x01(\v2\x1b.cedar_policy_core.EntitiesR\bentities\x12\x1c\n" +
	"\titeration\x18\x05 \x01(\rR\titeration*\xc1\x01\n" +
	"\x05ExtOp\x12\x0e\n" +
	"\n" +
	"DecimalVal\x10\x00\x12\x0e\n" +
	"\n" +
	"IPaddrIsV4\x10\x01\x12\x10\n" +
	"\fIPaddrAddrV4\x10\x02\x12\x12\n" +
	"\x0eIPaddrPrefixV4\x10\x03\x12\x10\n" +
	"\fIPaddrAddrV6\x10\x04\x12\x12\n" +
	"\x0eIPaddrPrefixV6\x10\x05\x12\x0f\n" +
	"\vDatetimeVal\x10\x06\x12\x14\n" +
	"\x10DatetimeOfBitVec\x10\a\x12\x0f\n" +
	"\vDurationVal\x10\b\x12\x14\n" +
	"\x10DurationOfBitVec\x10\t*N\n" +
	"\aExtType\x12\x0e\n" +
	"\n" +
	"IpAddrType\x10\x00\x12\x0f\n" +
	"\vDecimalType\x10\x01\x12\x10\n" +
	"\fDatetimeType\x10\x02\x12\x10\n" +
	"\fDurationType\x10\x03b\x06proto3"

var (
	file_Messages_proto_rawDescOnce sync.Once
	file_Messages_proto_rawDescData []byte
)

func file_Messages_proto_rawDescGZIP() []byte {
	file_Messages_proto_rawDescOnce.Do(func() {
		file_Messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Messages_proto_rawDesc), len(file_Messages_proto_rawDesc)))
	})
	return file_Messages_proto_rawDescData
}

var file_Messages_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_Messages_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_Messages_proto_goTypes = []any{
	(ExtOp)(0),                       // 0: cedar_proto_ffi.ExtOp
	(ExtType)(0),                     // 1: cedar_proto_ffi.ExtType
	(Op_BaseOp)(0),                   // 2: cedar_proto_ffi.Op.BaseOp
	(TermPrimType_Prim)(0),           // 3: cedar_proto_ffi.TermPrimType.Prim
	(*Policy)(nil),                   // 4: cedar_proto_ffi.Policy
	(*AuthorizationRequest)(nil),     // 5: cedar_proto_ffi.AuthorizationRequest
	(*EvaluationRequestChecked)(nil), // 6: cedar_proto_ffi.EvaluationRequestChecked
	(*EntityValidationRequest)(nil),  // 7: cedar_proto_ffi.EntityValidationRequest
	(*RequestValidationRequest)(nil), // 8: cedar_proto_ffi.RequestValidationRequest
	(*ValidationRequest)(nil),        // 9: cedar_proto_ffi.ValidationRequest
	(*LevelValidationRequest)(nil),   // 10: cedar_proto_ffi.LevelValidationRequest
	(*RequestEnv)(nil),               // 11: cedar_proto_ffi.RequestEnv
	(*CheckPolicyRequest)(nil),       // 12: cedar_proto_ffi.CheckPolicyRequest
	(*CheckPolicySetRequest)(nil),    // 13: cedar_proto_ffi.CheckPolicySetRequest
	(*ComparePoliciesRequest)(nil),   // 14: cedar_proto_ffi.ComparePoliciesRequest
	(*ComparePolicySetsRequest)(nil), // 15: cedar_proto_ffi.ComparePolicySetsRequest
	(*UUF)(nil),                      // 16: cedar_proto_ffi.UUF
	(*PatElem)(nil),                  // 17: cedar_proto_ffi.PatElem
	(*Pattern)(nil),                  // 18: cedar_proto_ffi.Pattern
	(*Op)(nil),                       // 19: cedar_proto_ffi.Op
	(*Bitvec)(nil),                   // 20: cedar_proto_ffi.Bitvec
	(*Decimal)(nil),                  // 21: cedar_proto_ffi.Decimal
	(*IpAddr)(nil),                   // 22: cedar_proto_ffi.IpAddr
	(*Datetime)(nil),                 // 23: cedar_proto_ffi.Datetime
	(*Duration)(nil),                 // 24: cedar_proto_ffi.Duration
	(*TermPrimType)(nil),             // 25: cedar_proto_ffi.TermPrimType
	(*TermType)(nil),                 // 26: cedar_proto_ffi.TermType
	(*TermVar)(nil),                  // 27: cedar_proto_ffi.TermVar
	(*Ext)(nil),                      // 28: cedar_proto_ffi.Ext
	(*TermPrim)(nil),                 // 29: cedar_proto_ffi.TermPrim
	(*Term)(nil),                     // 30: cedar_proto_ffi.Term
	(*Asserts)(nil),                  // 31: cedar_proto_ffi.Asserts
	(*CheckAssertsRequest)(nil),      // 32: cedar_proto_ffi.CheckAssertsRequest
	(*BatchedEvaluationRequest)(nil), // 33: cedar_proto_ffi.BatchedEvaluationRequest
	(*IpAddr_Cidr)(nil),              // 34: cedar_proto_ffi.IpAddr.Cidr
	(*TermType_RecordField)(nil),     // 35: cedar_proto_ffi.TermType.RecordField
	(*TermType_RecordType)(nil),      // 36: cedar_proto_ffi.TermType.RecordType
	(*Term_Set)(nil),                 // 37: cedar_proto_ffi.Term.Set
	(*Term_RecordField)(nil),         // 38: cedar_proto_ffi.Term.RecordField
	(*Term_Record)(nil),              // 39: cedar_proto_ffi.Term.Record
	(*Term_App)(nil),                 // 40: cedar_proto_ffi.Term.App
	(*core.TemplateBody)(nil),        // 41: cedar_policy_core.TemplateBody
	(*core.Policy)(nil),              // 42: cedar_policy_core.Policy
	(*core.Request)(nil),             // 43: cedar_policy_core.Request
	(*core.PolicySet)(nil),           // 44: cedar_policy_core.PolicySet
	(*core.Entities)(nil),            // 45: cedar_policy_core.Entities
	(*core.Expr)(nil),                // 46: cedar_policy_core.Expr
	(*validator.Schema)(nil),         // 47: cedar_policy_validator.Schema
	(validator.ValidationMode)(0),    // 48: cedar_policy_validator.ValidationMode
	(*core.Name)(nil),                // 49: cedar_policy_core.Name
	(*core.EntityUid)(nil),           // 50: cedar_policy_core.EntityUid
}
var file_Messages_proto_depIdxs = []int32{
	41, // 0: cedar_proto_ffi.Policy.template:type_name -> cedar_policy_core.TemplateBody
	42, // 1: cedar_proto_ffi.Policy.policy:type_name -> cedar_policy_core.Policy
	43, // 2: cedar_proto_ffi.AuthorizationRequest.request:type_name -> cedar_policy_core.Request
	44, // 3: cedar_proto_ffi.AuthorizationRequest.policies:type_name -> cedar_policy_core.PolicySet
	45, // 4: cedar_proto_ffi.AuthorizationRequest.entities:type_name -> cedar_policy_core.Entities
	46, // 5: cedar_proto_ffi.EvaluationRequestChecked.expr:type_name -> cedar_policy_core.Expr
	43, // 6: cedar_proto_ffi.EvaluationRequestChecked.request:type_name -> cedar_policy_core.Request
	45, // 7: cedar_proto_ffi.EvaluationRequestChecked.entities:type_name -> cedar_policy_core.Entities
	46, // 8: cedar_proto_ffi.EvaluationRequestChecked.expected:type_name -> cedar_policy_core.Expr
	47, // 9: cedar_proto_ffi.EntityValidationRequest.schema:type_name -> cedar_policy_validator.Schema
	45, // 10: cedar_proto_ffi.EntityValidationRequest.entities:type_name -> cedar_policy_core.Entities
	47, // 11: cedar_proto_ffi.RequestValidationRequest.schema:type_name -> cedar_policy_validator.Schema
	43, // 12: cedar_proto_ffi.RequestValidationRequest.request:type_name -> cedar_policy_core.Request
	47, // 13: cedar_proto_ffi.ValidationRequest.schema:type_name -> cedar_policy_validator.Schema
	44, // 14: cedar_proto_ffi.ValidationRequest.policies:type_name -> cedar_policy_core.PolicySet
	48, // 15: cedar_proto_ffi.ValidationRequest.mode:type_name -> cedar_policy_validator.ValidationMode
	47, // 16: cedar_proto_ffi.LevelValidationRequest.schema:type_name -> cedar_policy_validator.Schema
	44, // 17: cedar_proto_ffi.LevelValidationRequest.policies:type_name -> cedar_policy_core.PolicySet
	49, // 18: cedar_proto_ffi.RequestEnv.principal:type_name -> cedar_policy_core.Name
	50, // 19: cedar_proto_ffi.RequestEnv.action:type_name -> cedar_policy_core.EntityUid
	49, // 20: cedar_proto_ffi.RequestEnv.resource:type_name -> cedar_policy_core.Name
	4,  // 21: cedar_proto_ffi.CheckPolicyRequest.policy:type_name -> cedar_proto_ffi.Policy
	11, // 22: cedar_proto_ffi.CheckPolicyRequest.request:type_name -> cedar_proto_ffi.RequestEnv
	44, // 23: cedar_proto_ffi.CheckPolicySetRequest.policySet:type_name -> cedar_policy_core.PolicySet
	11, // 24: cedar_proto_ffi.CheckPolicySetRequest.request:type_name -> cedar_proto_ffi.RequestEnv
	4,  // 25: cedar_proto_ffi.ComparePoliciesRequest.policy1:type_name -> cedar_proto_ffi.Policy
	4,  // 26: cedar_proto_ffi.ComparePoliciesRequest.policy2:type_name -> cedar_proto_ffi.Policy
	11, // 27: cedar_proto_ffi.ComparePoliciesRequest.request:type_name -> cedar_proto_ffi.RequestEnv
	44, // 28: cedar_proto_ffi.ComparePolicySetsRequest.srcPolicySet:type_name -> cedar_policy_core.PolicySet
	44, // 29: cedar_proto_ffi.ComparePolicySetsRequest.tgtPolicySet:type_name -> cedar_policy_core.PolicySet
	11, // 30: cedar_proto_ffi.ComparePolicySetsRequest.request:type_name -> cedar_proto_ffi.RequestEnv
	26, // 31: cedar_proto_ffi.UUF.arg:type_name -> cedar_proto_ffi.TermType
	26, // 32: cedar_proto_ffi.UUF.out:type_name -> cedar_proto_ffi.TermType
	17, // 33: cedar_proto_ffi.Pattern.pattern:type_name -> cedar_proto_ffi.PatElem
	2,  // 34: cedar_proto_ffi.Op.base_op:type_name -> cedar_proto_ffi.Op.BaseOp
	16, // 35: cedar_proto_ffi.Op.uuf:type_name -> cedar_proto_ffi.UUF
	18, // 36: cedar_proto_ffi.Op.string_like:type_name -> cedar_proto_ffi.Pattern
	0,  // 37: cedar_proto_ffi.Op.ext_op:type_name -> cedar_proto_ffi.ExtOp
	34, // 38: cedar_proto_ffi.IpAddr.v4:type_name -> cedar_proto_ffi.IpAddr.Cidr
	34, // 39: cedar_proto_ffi.IpAddr.v6:type_name -> cedar_proto_ffi.IpAddr.Cidr
	3,  // 40: cedar_proto_ffi.TermPrimType.prim:type_name -> cedar_proto_ffi.TermPrimType.Prim
	49, // 41: cedar_proto_ffi.TermPrimType.entity:type_name -> cedar_policy_core.Name
	1,  // 42: cedar_proto_ffi.TermPrimType.ext:type_name -> cedar_proto_ffi.ExtType
	25, // 43: cedar_proto_ffi.TermType.prim:type_name -> cedar_proto_ffi.TermPrimType
	26, // 44: cedar_proto_ffi.TermType.option:type_name -> cedar_proto_ffi.TermType
	26, // 45: cedar_proto_ffi.TermType.set:type_name -> cedar_proto_ffi.TermType
	36, // 46: cedar_proto_ffi.TermType.record:type_name -> cedar_proto_ffi.TermType.RecordType
	26, // 47: cedar_proto_ffi.TermVar.ty:type_name -> cedar_proto_ffi.TermType
	21, // 48: cedar_proto_ffi.Ext.decimal:type_name -> cedar_proto_ffi.Decimal
	22, // 49: cedar_proto_ffi.Ext.ipaddr:type_name -> cedar_proto_ffi.IpAddr
	23, // 50: cedar_proto_ffi.Ext.datetime:type_name -> cedar_proto_ffi.Datetime
	24, // 51: cedar_proto_ffi.Ext.duration:type_name -> cedar_proto_ffi.Duration
	20, // 52: cedar_proto_ffi.TermPrim.bitvec:type_name -> cedar_proto_ffi.Bitvec
	50, // 53: cedar_proto_ffi.TermPrim.entity:type_name -> cedar_policy_core.EntityUid
	28, // 54: cedar_proto_ffi.TermPrim.ext:type_name -> cedar_proto_ffi.Ext
	29, // 55: cedar_proto_ffi.Term.prim:type_name -> cedar_proto_ffi.TermPrim
	27, // 56: cedar_proto_ffi.Term.var:type_name -> cedar_proto_ffi.TermVar
	26, // 57: cedar_proto_ffi.Term.none:type_name -> cedar_proto_ffi.TermType
	30, // 58: cedar_proto_ffi.Term.some:type_name -> cedar_proto_ffi.Term
	37, // 59: cedar_proto_ffi.Term.set:type_name -> cedar_proto_ffi.Term.Set
	39, // 60: cedar_proto_ffi.Term.record:type_name -> cedar_proto_ffi.Term.Record
	40, // 61: cedar_proto_ffi.Term.app:type_name -> cedar_proto_ffi.Term.App
	30, // 62: cedar_proto_ffi.Asserts.asserts:type_name -> cedar_proto_ffi.Term
	31, // 63: cedar_proto_ffi.CheckAssertsRequest.asserts:type_name -> cedar_proto_ffi.Asserts
	11, // 64: cedar_proto_ffi.CheckAssertsRequest.request:type_name -> cedar_proto_ffi.RequestEnv
	44, // 65: cedar_proto_ffi.BatchedEvaluationRequest.policies:type_name -> cedar_policy_core.PolicySet
	47, // 66: cedar_proto_ffi.BatchedEvaluationRequest.schema:type_name -> cedar_policy_validator.Schema
	43, // 67: cedar_proto_ffi.BatchedEvaluationRequest.request:type_name -> cedar_policy_core.Request
	45, // 68: cedar_proto_ffi.BatchedEvaluationRequest.entities:type_name -> cedar_policy_core.Entities
	20, // 69: cedar_proto_ffi.IpAddr.Cidr.addr:type_name -> cedar_proto_ffi.Bitvec
	20, // 70: cedar_proto_ffi.IpAddr.Cidr.pre:type_name -> cedar_proto_ffi.Bitvec
	26, // 71: cedar_proto_ffi.TermType.RecordField.ty:type_name -> cedar_proto_ffi.TermType
	35, // 72: cedar_proto_ffi.TermType.RecordType.fields:type_name -> cedar_proto_ffi.TermType.RecordField
	30, // 73: cedar_proto_ffi.Term.Set.elts:type_name -> cedar_proto_ffi.Term
	26, // 74: cedar_proto_ffi.Term.Set.elt_ty:type_name -> cedar_proto_ffi.TermType
	30, // 75: cedar_proto_ffi.Term.RecordField.term:type_name -> cedar_proto_ffi.Term
	38, // 76: cedar_proto_ffi.Term.Record.fields:type_name -> cedar_proto_ffi.Term.RecordField
	19, // 77: cedar_proto_ffi.Term.App.op:type_name -> cedar_proto_ffi.Op
	30, // 78: cedar_proto_ffi.Term.App.args:type_name -> cedar_proto_ffi.Term
	26, // 79: cedar_proto_ffi.Term.App.ret_ty:type_name -> cedar_proto_ffi.TermType
	80, // [80:80] is the sub-list for method output_type
	80, // [80:80] is the sub-list for method input_type
	80, // [80:80] is the sub-list for extension type_name
	80, // [80:80] is the sub-list for extension extendee
	0,  // [0:80] is the sub-list for field type_name
}

func init() { file_Messages_proto_init() }
func file_Messages_proto_init() {
	if File_Messages_proto != nil {
		return
	}
	file_Messages_proto_msgTypes[13].OneofWrappers = []any{
		(*PatElem_Star)(nil),
		(*PatElem_Char)(nil),
	}
	file_Messages_proto_msgTypes[15].OneofWrappers = []any{
		(*Op_BaseOp_)(nil),
		(*Op_Uuf)(nil),
		(*Op_ZeroExtend)(nil),
		(*Op_RecordGet)(nil),
		(*Op_StringLike)(nil),
		(*Op_ExtOp)(nil),
	}
	file_Messages_proto_msgTypes[18].OneofWrappers = []any{
		(*IpAddr_V4)(nil),
		(*IpAddr_V6)(nil),
	}
	file_Messages_proto_msgTypes[21].OneofWrappers = []any{
		(*TermPrimType_Prim_)(nil),
		(*TermPrimType_Bitvec)(nil),
		(*TermPrimType_Entity)(nil),
		(*TermPrimType_Ext)(nil),
	}
	file_Messages_proto_msgTypes[22].OneofWrappers = []any{
		(*TermType_Prim)(nil),
		(*TermType_Option)(nil),
		(*TermType_Set)(nil),
		(*TermType_Record)(nil),
	}
	file_Messages_proto_msgTypes[24].OneofWrappers = []any{
		(*Ext_Decimal)(nil),
		(*Ext_Ipaddr)(nil),
		(*Ext_Datetime)(nil),
		(*Ext_Duration)(nil),
	}
	file_Messages_proto_msgTypes[25].OneofWrappers = []any{
		(*TermPrim_Bool)(nil),
		(*TermPrim_Bitvec)(nil),
		(*TermPrim_String_)(nil),
		(*TermPrim_Entity)(nil),
		(*TermPrim_Ext)(nil),
	}
	file_Messages_proto_msgTypes[26].OneofWrappers = []any{
		(*Term_Prim)(nil),
		(*Term_Var)(nil),
		(*Term_None)(nil),
		(*Term_Some)(nil),
		(*Term_Set_)(nil),
		(*Term_Record_)(nil),
		(*Term_App_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Messages_proto_rawDesc), len(file_Messages_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Messages_proto_goTypes,
		DependencyIndexes: file_Messages_proto_depIdxs,
		EnumInfos:         file_Messages_proto_enumTypes,
		MessageInfos:      file_Messages_proto_msgTypes,
	}.Build()
	File_Messages_proto = out.File
	file_Messages_proto_goTypes = nil
	file_Messages_proto_depIdxs = nil
}
