//
// Copyright Cedar Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: validator.proto

package validator

import (
	core "github.com/cedar-policy/cedar-spec/cedar-go-drt/internal/proto/pb/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationMode int32

const (
	ValidationMode_Strict     ValidationMode = 0
	ValidationMode_Permissive ValidationMode = 1
	ValidationMode_Partial    ValidationMode = 2
)

// Enum value maps for ValidationMode.
var (
	ValidationMode_name = map[int32]string{
		0: "Strict",
		1: "Permissive",
		2: "Partial",
	}
	ValidationMode_value = map[string]int32{
		"Strict":     0,
		"Permissive": 1,
		"Partial":    2,
	}
)

func (x ValidationMode) Enum() *ValidationMode {
	p := new(ValidationMode)
	*p = x
	return p
}

func (x ValidationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_validator_proto_enumTypes[0].Descriptor()
}

func (ValidationMode) Type() protoreflect.EnumType {
	return &file_validator_proto_enumTypes[0]
}

func (x ValidationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationMode.Descriptor instead.
func (ValidationMode) EnumDescriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{0}
}

type Type_Prim int32

const (
	Type_String Type_Prim = 0
	Type_Bool   Type_Prim = 1
	Type_Long   Type_Prim = 2
)

// Enum value maps for Type_Prim.
var (
	Type_Prim_name = map[int32]string{
		0: "String",
		1: "Bool",
		2: "Long",
	}
	Type_Prim_value = map[string]int32{
		"String": 0,
		"Bool":   1,
		"Long":   2,
	}
)

func (x Type_Prim) Enum() *Type_Prim {
	p := new(Type_Prim)
	*p = x
	return p
}

func (x Type_Prim) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type_Prim) Descriptor() protoreflect.EnumDescriptor {
	return file_validator_proto_enumTypes[1].Descriptor()
}

func (Type_Prim) Type() protoreflect.EnumType {
	return &file_validator_proto_enumTypes[1]
}

func (x Type_Prim) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type_Prim.Descriptor instead.
func (Type_Prim) EnumDescriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{3, 0}
}

// the protobuf Schema message describes a complete schema.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityDecls   []*EntityDecl          `protobuf:"bytes,1,rep,name=entity_decls,json=entityDecls,proto3" json:"entity_decls,omitempty"`
	ActionDecls   []*ActionDecl          `protobuf:"bytes,2,rep,name=action_decls,json=actionDecls,proto3" json:"action_decls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetEntityDecls() []*EntityDecl {
	if x != nil {
		return x.EntityDecls
	}
	return nil
}

func (x *Schema) GetActionDecls() []*ActionDecl {
	if x != nil {
		return x.ActionDecls
	}
	return nil
}

// the protobuf EntityDecl message contains all of the schema's
// information about a single entity type.
type EntityDecl struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          *core.Name                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Descendants   []*core.Name              `protobuf:"bytes,2,rep,name=descendants,proto3" json:"descendants,omitempty"`
	Attributes    map[string]*AttributeType `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          *Type                     `protobuf:"bytes,5,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	EnumChoices   []string                  `protobuf:"bytes,6,rep,name=enum_choices,json=enumChoices,proto3" json:"enum_choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDecl) Reset() {
	*x = EntityDecl{}
	mi := &file_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDecl) ProtoMessage() {}

func (x *EntityDecl) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDecl.ProtoReflect.Descriptor instead.
func (*EntityDecl) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{1}
}

func (x *EntityDecl) GetName() *core.Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *EntityDecl) GetDescendants() []*core.Name {
	if x != nil {
		return x.Descendants
	}
	return nil
}

func (x *EntityDecl) GetAttributes() map[string]*AttributeType {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *EntityDecl) GetTags() *Type {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EntityDecl) GetEnumChoices() []string {
	if x != nil {
		return x.EnumChoices
	}
	return nil
}

// the protobuf ActionDecl message contains all of the schema's
// information about a single action.
type ActionDecl struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Name           *core.EntityUid           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Descendants    []*core.EntityUid         `protobuf:"bytes,3,rep,name=descendants,proto3" json:"descendants,omitempty"`
	Context        map[string]*AttributeType `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PrincipalTypes []*core.Name              `protobuf:"bytes,5,rep,name=principal_types,json=principalTypes,proto3" json:"principal_types,omitempty"`
	ResourceTypes  []*core.Name              `protobuf:"bytes,6,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionDecl) Reset() {
	*x = ActionDecl{}
	mi := &file_validator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDecl) ProtoMessage() {}

func (x *ActionDecl) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDecl.ProtoReflect.Descriptor instead.
func (*ActionDecl) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{2}
}

func (x *ActionDecl) GetName() *core.EntityUid {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ActionDecl) GetDescendants() []*core.EntityUid {
	if x != nil {
		return x.Descendants
	}
	return nil
}

func (x *ActionDecl) GetContext() map[string]*AttributeType {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ActionDecl) GetPrincipalTypes() []*core.Name {
	if x != nil {
		return x.PrincipalTypes
	}
	return nil
}

func (x *ActionDecl) GetResourceTypes() []*core.Name {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Type_Prim_
	//	*Type_SetElem
	//	*Type_Entity
	//	*Type_Record_
	//	*Type_Ext
	Data          isType_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_validator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{3}
}

func (x *Type) GetData() isType_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Type) GetPrim() Type_Prim {
	if x != nil {
		if x, ok := x.Data.(*Type_Prim_); ok {
			return x.Prim
		}
	}
	return Type_String
}

func (x *Type) GetSetElem() *Type {
	if x != nil {
		if x, ok := x.Data.(*Type_SetElem); ok {
			return x.SetElem
		}
	}
	return nil
}

func (x *Type) GetEntity() *core.Name {
	if x != nil {
		if x, ok := x.Data.(*Type_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *Type) GetRecord() *Type_Record {
	if x != nil {
		if x, ok := x.Data.(*Type_Record_); ok {
			return x.Record
		}
	}
	return nil
}

func (x *Type) GetExt() *core.Name {
	if x != nil {
		if x, ok := x.Data.(*Type_Ext); ok {
			return x.Ext
		}
	}
	return nil
}

type isType_Data interface {
	isType_Data()
}

type Type_Prim_ struct {
	// Primitive types
	Prim Type_Prim `protobuf:"varint,1,opt,name=prim,proto3,enum=cedar_policy_validator.Type_Prim,oneof"`
}

type Type_SetElem struct {
	// Set with the specified element type
	SetElem *Type `protobuf:"bytes,2,opt,name=set_elem,json=setElem,proto3,oneof"`
}

type Type_Entity struct {
	// Entity type
	Entity *core.Name `protobuf:"bytes,3,opt,name=entity,proto3,oneof"`
}

type Type_Record_ struct {
	// Record type
	// Map types are not allowed inside oneof, so we can't inline the map here
	Record *Type_Record `protobuf:"bytes,4,opt,name=record,proto3,oneof"`
}

type Type_Ext struct {
	// Extension type
	Ext *core.Name `protobuf:"bytes,5,opt,name=ext,proto3,oneof"`
}

func (*Type_Prim_) isType_Data() {}

func (*Type_SetElem) isType_Data() {}

func (*Type_Entity) isType_Data() {}

func (*Type_Record_) isType_Data() {}

func (*Type_Ext) isType_Data() {}

type AttributeType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrType      *Type                  `protobuf:"bytes,1,opt,name=attr_type,json=attrType,proto3" json:"attr_type,omitempty"`
	IsRequired    bool                   `protobuf:"varint,2,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeType) Reset() {
	*x = AttributeType{}
	mi := &file_validator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeType) ProtoMessage() {}

func (x *AttributeType) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeType.ProtoReflect.Descriptor instead.
func (*AttributeType) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeType) GetAttrType() *Type {
	if x != nil {
		return x.AttrType
	}
	return nil
}

func (x *AttributeType) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

type Type_Record struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Attrs         map[string]*AttributeType `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type_Record) Reset() {
	*x = Type_Record{}
	mi := &file_validator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Record) ProtoMessage() {}

func (x *Type_Record) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Record.ProtoReflect.Descriptor instead.
func (*Type_Record) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Type_Record) GetAttrs() map[string]*AttributeType {
	if x != nil {
		return x.Attrs
	}
	return nil
}

var File_validator_proto protoreflect.FileDescriptor

const file_validator_proto_rawDesc = "" +
	"\n" +
	"\x0fvalidator.proto\x12\x16cedar_policy_validator\x1a\n" +
	"core.proto\"\x96\x01\n" +
	"\x06Schema\x12E\n" +
	"\fentity_decls\x18\x01 \x03(\v2\".cedar_policy_validator.EntityDeclR\ventityDecls\x12E\n" +
	"\faction_decls\x18\x02 \x03(\v2\".cedar_policy_validator.ActionDeclR\vactionDecls\"\x91\x03\n" +
	"\n" +
	"EntityDecl\x12+\n" +
	"\x04name\x18\x01 \x01(\v2\x17.cedar_policy_core.NameR\x04name\x129\n" +
	"\vdescendants\x18\x02 \x03(\v2\x17.cedar_policy_core.NameR\vdescendants\x12R\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v22.cedar_policy_validator.EntityDecl.AttributesEntryR\n" +
	"attributes\x125\n" +
	"\x04tags\x18\x05 \x01(\v2\x1c.cedar_policy_validator.TypeH\x00R\x04tags\x88\x01\x01\x12!\n" +
	"\fenum_choices\x18\x06 \x03(\tR\venumChoices\x1ad\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.cedar_policy_validator.AttributeTypeR\x05value:\x028\x01B\a\n" +
	"\x05_tags\"\xae\x03\n" +
	"\n" +
	"ActionDecl\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.cedar_policy_core.EntityUidR\x04name\x12>\n" +
	"\vdescendants\x18\x03 \x03(\v2\x1c.cedar_policy_core.EntityUidR\vdescendants\x12I\n" +
	"\acontext\x18\x04 \x03(\v2/.cedar_policy_validator.ActionDecl.ContextEntryR\acontext\x12@\n" +
	"\x0fprincipal_types\x18\x05 \x03(\v2\x17.cedar_policy_core.NameR\x0eprincipalTypes\x12>\n" +
	"\x0eresource_types\x18\x06 \x03(\v2\x17.cedar_policy_core.NameR\rresourceTypes\x1aa\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.cedar_policy_validator.AttributeTypeR\x05value:\x028\x01\"\xfb\x03\n" +
	"\x04Type\x127\n" +
	"\x04prim\x18\x01 \x01(\x0e2!.cedar_policy_validator.Type.PrimH\x00R\x04prim\x129\n" +
	"\bset_elem\x18\x02 \x01(\v2\x1c.cedar_policy_validator.TypeH\x00R\asetElem\x121\n" +
	"\x06entity\x18\x03 \x01(\v2\x17.cedar_policy_core.NameH\x00R\x06entity\x12=\n" +
	"\x06record\x18\x04 \x01(\v2#.cedar_policy_validator.Type.RecordH\x00R\x06record\x12+\n" +
	"\x03ext\x18\x05 \x01(\v2\x17.cedar_policy_core.NameH\x00R\x03ext\x1a\xaf\x01\n" +
	"\x06Record\x12D\n" +
	"\x05attrs\x18\x01 \x03(\v2..cedar_policy_validator.Type.Record.AttrsEntryR\x05attrs\x1a_\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.cedar_policy_validator.AttributeTypeR\x05value:\x028\x01\"&\n" +
	"\x04Prim\x12\n" +
	"\n" +
	"\x06String\x10\x00\x12\b\n" +
	"\x04Bool\x10\x01\x12\b\n" +
	"\x04Long\x10\x02B\x06\n" +
	"\x04data\"k\n" +
	"\rAttributeType\x129\n" +
	"\tattr_type\x18\x01 \x01(\v2\x1c.cedar_policy_validator.TypeR\battrType\x12\x1f\n" +
	"\vis_required\x18\x02 \x01(\bR\n" +
	"isRequired*9\n" +
	"\x0eValidationMode\x12\n" +
	"\n" +
	"\x06Strict\x10\x00\x12\x0e\n" +
	"\n" +
	"Permissive\x10\x01\x12\v\n" +
	"\aPartial\x10\x02b\x06proto3"

var (
	file_validator_proto_rawDescOnce sync.Once
	file_validator_proto_rawDescData []byte
)

func file_validator_proto_rawDescGZIP() []byte {
	file_validator_proto_rawDescOnce.Do(func() {
		file_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)))
	})
	return file_validator_proto_rawDescData
}

var file_validator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_validator_proto_goTypes = []any{
	(ValidationMode)(0),    // 0: cedar_policy_validator.ValidationMode
	(Type_Prim)(0),         // 1: cedar_policy_validator.Type.Prim
	(*Schema)(nil),         // 2: cedar_policy_validator.Schema
	(*EntityDecl)(nil),     // 3: cedar_policy_validator.EntityDecl
	(*ActionDecl)(nil),     // 4: cedar_policy_validator.ActionDecl
	(*Type)(nil),           // 5: cedar_policy_validator.Type
	(*AttributeType)(nil),  // 6: cedar_policy_validator.AttributeType
	nil,                    // 7: cedar_policy_validator.EntityDecl.AttributesEntry
	nil,                    // 8: cedar_policy_validator.ActionDecl.ContextEntry
	(*Type_Record)(nil),    // 9: cedar_policy_validator.Type.Record
	nil,                    // 10: cedar_policy_validator.Type.Record.AttrsEntry
	(*core.Name)(nil),      // 11: cedar_policy_core.Name
	(*core.EntityUid)(nil), // 12: cedar_policy_core.EntityUid
}
var file_validator_proto_depIdxs = []int32{
	3,  // 0: cedar_policy_validator.Schema.entity_decls:type_name -> cedar_policy_validator.EntityDecl
	4,  // 1: cedar_policy_validator.Schema.action_decls:type_name -> cedar_policy_validator.ActionDecl
	11, // 2: cedar_policy_validator.EntityDecl.name:type_name -> cedar_policy_core.Name
	11, // 3: cedar_policy_validator.EntityDecl.descendants:type_name -> cedar_policy_core.Name
	7,  // 4: cedar_policy_validator.EntityDecl.attributes:type_name -> cedar_policy_validator.EntityDecl.AttributesEntry
	5,  // 5: cedar_policy_validator.EntityDecl.tags:type_name -> cedar_policy_validator.Type
	12, // 6: cedar_policy_validator.ActionDecl.name:type_name -> cedar_policy_core.EntityUid
	12, // 7: cedar_policy_validator.ActionDecl.descendants:type_name -> cedar_policy_core.EntityUid
	8,  // 8: cedar_policy_validator.ActionDecl.context:type_name -> cedar_policy_validator.ActionDecl.ContextEntry
	11, // 9: cedar_policy_validator.ActionDecl.principal_types:type_name -> cedar_policy_core.Name
	11, // 10: cedar_policy_validator.ActionDecl.resource_types:type_name -> cedar_policy_core.Name
	1,  // 11: cedar_policy_validator.Type.prim:type_name -> cedar_policy_validator.Type.Prim
	5,  // 12: cedar_policy_validator.Type.set_elem:type_name -> cedar_policy_validator.Type
	11, // 13: cedar_policy_validator.Type.entity:type_name -> cedar_policy_core.Name
	9,  // 14: cedar_policy_validator.Type.record:type_name -> cedar_policy_validator.Type.Record
	11, // 15: cedar_policy_validator.Type.ext:type_name -> cedar_policy_core.Name
	5,  // 16: cedar_policy_validator.AttributeType.attr_type:type_name -> cedar_policy_validator.Type
	6,  // 17: cedar_policy_validator.EntityDecl.AttributesEntry.value:type_name -> cedar_policy_validator.AttributeType
	6,  // 18: cedar_policy_validator.ActionDecl.ContextEntry.value:type_name -> cedar_policy_validator.AttributeType
	10, // 19: cedar_policy_validator.Type.Record.attrs:type_name -> cedar_policy_validator.Type.Record.AttrsEntry
	6,  // 20: cedar_policy_validator.Type.Record.AttrsEntry.value:type_name -> cedar_policy_validator.AttributeType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_validator_proto_init() }
func file_validator_proto_init() {
	if File_validator_proto != nil {
		return
	}
	file_validator_proto_msgTypes[1].OneofWrappers = []any{}
	file_validator_proto_msgTypes[3].OneofWrappers = []any{
		(*Type_Prim_)(nil),
		(*Type_SetElem)(nil),
		(*Type_Entity)(nil),
		(*Type_Record_)(nil),
		(*Type_Ext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validator_proto_goTypes,
		DependencyIndexes: file_validator_proto_depIdxs,
		EnumInfos:         file_validator_proto_enumTypes,
		MessageInfos:      file_validator_proto_msgTypes,
	}.Build()
	File_validator_proto = out.File
	file_validator_proto_goTypes = nil
	file_validator_proto_depIdxs = nil
}
