//
// Copyright Cedar Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect int32

const (
	Effect_Forbid Effect = 0
	Effect_Permit Effect = 1
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "Forbid",
		1: "Permit",
	}
	Effect_value = map[string]int32{
		"Forbid": 0,
		"Permit": 1,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type SlotId int32

const (
	SlotId_Principal SlotId = 0
	SlotId_Resource  SlotId = 1
)

// Enum value maps for SlotId.
var (
	SlotId_name = map[int32]string{
		0: "Principal",
		1: "Resource",
	}
	SlotId_value = map[string]int32{
		"Principal": 0,
		"Resource":  1,
	}
)

func (x SlotId) Enum() *SlotId {
	p := new(SlotId)
	*p = x
	return p
}

func (x SlotId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotId) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[1].Descriptor()
}

func (SlotId) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[1]
}

func (x SlotId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotId.Descriptor instead.
func (SlotId) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

// if it's a Slot, we know from context which Slot it is,
// so we don't need a `SlotId` and can just use this one-armed enum
type EntityReference_Slot int32

const (
	// the one option for the enum
	EntityReference_unit EntityReference_Slot = 0
)

// Enum value maps for EntityReference_Slot.
var (
	EntityReference_Slot_name = map[int32]string{
		0: "unit",
	}
	EntityReference_Slot_value = map[string]int32{
		"unit": 0,
	}
)

func (x EntityReference_Slot) Enum() *EntityReference_Slot {
	p := new(EntityReference_Slot)
	*p = x
	return p
}

func (x EntityReference_Slot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityReference_Slot) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[2].Descriptor()
}

func (EntityReference_Slot) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[2]
}

func (x EntityReference_Slot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityReference_Slot.Descriptor instead.
func (EntityReference_Slot) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7, 0}
}

// Zero-arity constructors represented as enums with only one member
type PrincipalOrResourceConstraint_Any int32

const (
	// the one option for the enum
	PrincipalOrResourceConstraint_unit PrincipalOrResourceConstraint_Any = 0
)

// Enum value maps for PrincipalOrResourceConstraint_Any.
var (
	PrincipalOrResourceConstraint_Any_name = map[int32]string{
		0: "unit",
	}
	PrincipalOrResourceConstraint_Any_value = map[string]int32{
		"unit": 0,
	}
)

func (x PrincipalOrResourceConstraint_Any) Enum() *PrincipalOrResourceConstraint_Any {
	p := new(PrincipalOrResourceConstraint_Any)
	*p = x
	return p
}

func (x PrincipalOrResourceConstraint_Any) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalOrResourceConstraint_Any) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[3].Descriptor()
}

func (PrincipalOrResourceConstraint_Any) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[3]
}

func (x PrincipalOrResourceConstraint_Any) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalOrResourceConstraint_Any.Descriptor instead.
func (PrincipalOrResourceConstraint_Any) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8, 0}
}

// Zero-arity constructors represented as enums with only one member
type ActionConstraint_Any int32

const (
	// the one option for the enum
	ActionConstraint_unit ActionConstraint_Any = 0
)

// Enum value maps for ActionConstraint_Any.
var (
	ActionConstraint_Any_name = map[int32]string{
		0: "unit",
	}
	ActionConstraint_Any_value = map[string]int32{
		"unit": 0,
	}
)

func (x ActionConstraint_Any) Enum() *ActionConstraint_Any {
	p := new(ActionConstraint_Any)
	*p = x
	return p
}

func (x ActionConstraint_Any) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionConstraint_Any) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[4].Descriptor()
}

func (ActionConstraint_Any) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[4]
}

func (x ActionConstraint_Any) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionConstraint_Any.Descriptor instead.
func (ActionConstraint_Any) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9, 0}
}

type Expr_Var int32

const (
	Expr_Principal Expr_Var = 0
	Expr_Action    Expr_Var = 1
	Expr_Resource  Expr_Var = 2
	Expr_Context   Expr_Var = 3
)

// Enum value maps for Expr_Var.
var (
	Expr_Var_name = map[int32]string{
		0: "Principal",
		1: "Action",
		2: "Resource",
		3: "Context",
	}
	Expr_Var_value = map[string]int32{
		"Principal": 0,
		"Action":    1,
		"Resource":  2,
		"Context":   3,
	}
)

func (x Expr_Var) Enum() *Expr_Var {
	p := new(Expr_Var)
	*p = x
	return p
}

func (x Expr_Var) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expr_Var) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[5].Descriptor()
}

func (Expr_Var) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[5]
}

func (x Expr_Var) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expr_Var.Descriptor instead.
func (Expr_Var) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 0}
}

type Expr_UnaryApp_Op int32

const (
	Expr_UnaryApp_Not     Expr_UnaryApp_Op = 0
	Expr_UnaryApp_Neg     Expr_UnaryApp_Op = 1
	Expr_UnaryApp_IsEmpty Expr_UnaryApp_Op = 2
)

// Enum value maps for Expr_UnaryApp_Op.
var (
	Expr_UnaryApp_Op_name = map[int32]string{
		0: "Not",
		1: "Neg",
		2: "IsEmpty",
	}
	Expr_UnaryApp_Op_value = map[string]int32{
		"Not":     0,
		"Neg":     1,
		"IsEmpty": 2,
	}
)

func (x Expr_UnaryApp_Op) Enum() *Expr_UnaryApp_Op {
	p := new(Expr_UnaryApp_Op)
	*p = x
	return p
}

func (x Expr_UnaryApp_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expr_UnaryApp_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[6].Descriptor()
}

func (Expr_UnaryApp_Op) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[6]
}

func (x Expr_UnaryApp_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expr_UnaryApp_Op.Descriptor instead.
func (Expr_UnaryApp_Op) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 4, 0}
}

type Expr_BinaryApp_Op int32

const (
	Expr_BinaryApp_Eq          Expr_BinaryApp_Op = 0
	Expr_BinaryApp_Less        Expr_BinaryApp_Op = 1
	Expr_BinaryApp_LessEq      Expr_BinaryApp_Op = 2
	Expr_BinaryApp_Add         Expr_BinaryApp_Op = 3
	Expr_BinaryApp_Sub         Expr_BinaryApp_Op = 4
	Expr_BinaryApp_Mul         Expr_BinaryApp_Op = 5
	Expr_BinaryApp_In          Expr_BinaryApp_Op = 6
	Expr_BinaryApp_Contains    Expr_BinaryApp_Op = 7
	Expr_BinaryApp_ContainsAll Expr_BinaryApp_Op = 8
	Expr_BinaryApp_ContainsAny Expr_BinaryApp_Op = 9
	Expr_BinaryApp_GetTag      Expr_BinaryApp_Op = 10
	Expr_BinaryApp_HasTag      Expr_BinaryApp_Op = 11
)

// Enum value maps for Expr_BinaryApp_Op.
var (
	Expr_BinaryApp_Op_name = map[int32]string{
		0:  "Eq",
		1:  "Less",
		2:  "LessEq",
		3:  "Add",
		4:  "Sub",
		5:  "Mul",
		6:  "In",
		7:  "Contains",
		8:  "ContainsAll",
		9:  "ContainsAny",
		10: "GetTag",
		11: "HasTag",
	}
	Expr_BinaryApp_Op_value = map[string]int32{
		"Eq":          0,
		"Less":        1,
		"LessEq":      2,
		"Add":         3,
		"Sub":         4,
		"Mul":         5,
		"In":          6,
		"Contains":    7,
		"ContainsAll": 8,
		"ContainsAny": 9,
		"GetTag":      10,
		"HasTag":      11,
	}
)

func (x Expr_BinaryApp_Op) Enum() *Expr_BinaryApp_Op {
	p := new(Expr_BinaryApp_Op)
	*p = x
	return p
}

func (x Expr_BinaryApp_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expr_BinaryApp_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[7].Descriptor()
}

func (Expr_BinaryApp_Op) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[7]
}

func (x Expr_BinaryApp_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expr_BinaryApp_Op.Descriptor instead.
func (Expr_BinaryApp_Op) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 5, 0}
}

// Zero-arity constructors represented as enums with only one member
type Expr_Like_PatternElem_Wildcard int32

const (
	// the one option for the enum
	Expr_Like_PatternElem_unit Expr_Like_PatternElem_Wildcard = 0
)

// Enum value maps for Expr_Like_PatternElem_Wildcard.
var (
	Expr_Like_PatternElem_Wildcard_name = map[int32]string{
		0: "unit",
	}
	Expr_Like_PatternElem_Wildcard_value = map[string]int32{
		"unit": 0,
	}
)

func (x Expr_Like_PatternElem_Wildcard) Enum() *Expr_Like_PatternElem_Wildcard {
	p := new(Expr_Like_PatternElem_Wildcard)
	*p = x
	return p
}

func (x Expr_Like_PatternElem_Wildcard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expr_Like_PatternElem_Wildcard) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[8].Descriptor()
}

func (Expr_Like_PatternElem_Wildcard) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[8]
}

func (x Expr_Like_PatternElem_Wildcard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expr_Like_PatternElem_Wildcard.Descriptor instead.
func (Expr_Like_PatternElem_Wildcard) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 9, 0, 0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *EntityUid             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Action        *EntityUid             `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *EntityUid             `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       map[string]*Expr       `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPrincipal() *EntityUid {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *Request) GetAction() *EntityUid {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Request) GetResource() *EntityUid {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Request) GetContext() map[string]*Expr {
	if x != nil {
		return x.Context
	}
	return nil
}

// the protobuf PolicySet message describes a complete policy set, including
// templates, static policies, and/or template-linked policies.
type PolicySet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Both templates and static policies are included here, with static
	// policies represented as templates with zero slots.
	Templates []*TemplateBody `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	// All static policies and template-linked policies are included here.
	// Static policies must appear exactly once, and the PolicyID of the static
	// policy must be the same in this list and the above list.
	Links         []*Policy `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySet) Reset() {
	*x = PolicySet{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySet) ProtoMessage() {}

func (x *PolicySet) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySet.ProtoReflect.Descriptor instead.
func (*PolicySet) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySet) GetTemplates() []*TemplateBody {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *PolicySet) GetLinks() []*Policy {
	if x != nil {
		return x.Links
	}
	return nil
}

type Entities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entities) Reset() {
	*x = Entities{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entities) ProtoMessage() {}

func (x *Entities) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entities.ProtoReflect.Descriptor instead.
func (*Entities) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *Entities) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type EntityUid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            *Name                  `protobuf:"bytes,1,opt,name=ty,proto3" json:"ty,omitempty"`
	Eid           string                 `protobuf:"bytes,2,opt,name=eid,proto3" json:"eid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityUid) Reset() {
	*x = EntityUid{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityUid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityUid) ProtoMessage() {}

func (x *EntityUid) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityUid.ProtoReflect.Descriptor instead.
func (*EntityUid) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *EntityUid) GetTy() *Name {
	if x != nil {
		return x.Ty
	}
	return nil
}

func (x *EntityUid) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          []string               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *Name) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Name) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

// the protobuf Policy message describes either a static or a template-linked policy.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the template associated with this policy.
	// For static policies, this is the ID of a zero-slot template.
	TemplateId string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// ID of this policy itself.
	// For static policies, this is omitted/ignored; the ID of the policy is the
	// `template_id`.
	LinkId *string `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3,oneof" json:"link_id,omitempty"`
	// Whether this policy is a static (false) or template-linked (true) policy
	IsTemplateLink bool `protobuf:"varint,3,opt,name=is_template_link,json=isTemplateLink,proto3" json:"is_template_link,omitempty"`
	// Value of the `?principal` slot.
	// Omitted/ignored for templates without the `?principal` slot.
	PrincipalEuid *EntityUid `protobuf:"bytes,4,opt,name=principal_euid,json=principalEuid,proto3" json:"principal_euid,omitempty"`
	// Value of the `?resource` slot.
	// Omitted/ignored for templates without the `?resource` slot.
	ResourceEuid  *EntityUid `protobuf:"bytes,5,opt,name=resource_euid,json=resourceEuid,proto3" json:"resource_euid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *Policy) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Policy) GetLinkId() string {
	if x != nil && x.LinkId != nil {
		return *x.LinkId
	}
	return ""
}

func (x *Policy) GetIsTemplateLink() bool {
	if x != nil {
		return x.IsTemplateLink
	}
	return false
}

func (x *Policy) GetPrincipalEuid() *EntityUid {
	if x != nil {
		return x.PrincipalEuid
	}
	return nil
}

func (x *Policy) GetResourceEuid() *EntityUid {
	if x != nil {
		return x.ResourceEuid
	}
	return nil
}

type TemplateBody struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	Id                  string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Annotations         map[string]string              `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Effect              Effect                         `protobuf:"varint,4,opt,name=effect,proto3,enum=cedar_policy_core.Effect" json:"effect,omitempty"`
	PrincipalConstraint *PrincipalOrResourceConstraint `protobuf:"bytes,5,opt,name=principal_constraint,json=principalConstraint,proto3" json:"principal_constraint,omitempty"`
	ActionConstraint    *ActionConstraint              `protobuf:"bytes,6,opt,name=action_constraint,json=actionConstraint,proto3" json:"action_constraint,omitempty"`
	ResourceConstraint  *PrincipalOrResourceConstraint `protobuf:"bytes,7,opt,name=resource_constraint,json=resourceConstraint,proto3" json:"resource_constraint,omitempty"`
	NonScopeConstraints *Expr                          `protobuf:"bytes,8,opt,name=non_scope_constraints,json=nonScopeConstraints,proto3" json:"non_scope_constraints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TemplateBody) Reset() {
	*x = TemplateBody{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBody) ProtoMessage() {}

func (x *TemplateBody) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBody.ProtoReflect.Descriptor instead.
func (*TemplateBody) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateBody) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateBody) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *TemplateBody) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_Forbid
}

func (x *TemplateBody) GetPrincipalConstraint() *PrincipalOrResourceConstraint {
	if x != nil {
		return x.PrincipalConstraint
	}
	return nil
}

func (x *TemplateBody) GetActionConstraint() *ActionConstraint {
	if x != nil {
		return x.ActionConstraint
	}
	return nil
}

func (x *TemplateBody) GetResourceConstraint() *PrincipalOrResourceConstraint {
	if x != nil {
		return x.ResourceConstraint
	}
	return nil
}

func (x *TemplateBody) GetNonScopeConstraints() *Expr {
	if x != nil {
		return x.NonScopeConstraints
	}
	return nil
}

// an EntityReference may either be an EntityUid or a Slot.
type EntityReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*EntityReference_Slot_
	//	*EntityReference_Euid
	Data          isEntityReference_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityReference) Reset() {
	*x = EntityReference{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityReference) ProtoMessage() {}

func (x *EntityReference) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityReference.ProtoReflect.Descriptor instead.
func (*EntityReference) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *EntityReference) GetData() isEntityReference_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EntityReference) GetSlot() EntityReference_Slot {
	if x != nil {
		if x, ok := x.Data.(*EntityReference_Slot_); ok {
			return x.Slot
		}
	}
	return EntityReference_unit
}

func (x *EntityReference) GetEuid() *EntityUid {
	if x != nil {
		if x, ok := x.Data.(*EntityReference_Euid); ok {
			return x.Euid
		}
	}
	return nil
}

type isEntityReference_Data interface {
	isEntityReference_Data()
}

type EntityReference_Slot_ struct {
	Slot EntityReference_Slot `protobuf:"varint,1,opt,name=slot,proto3,enum=cedar_policy_core.EntityReference_Slot,oneof"`
}

type EntityReference_Euid struct {
	Euid *EntityUid `protobuf:"bytes,2,opt,name=euid,proto3,oneof"`
}

func (*EntityReference_Slot_) isEntityReference_Data() {}

func (*EntityReference_Euid) isEntityReference_Data() {}

type PrincipalOrResourceConstraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*PrincipalOrResourceConstraint_Any_
	//	*PrincipalOrResourceConstraint_In
	//	*PrincipalOrResourceConstraint_Eq
	//	*PrincipalOrResourceConstraint_Is
	//	*PrincipalOrResourceConstraint_IsIn
	Data          isPrincipalOrResourceConstraint_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalOrResourceConstraint) Reset() {
	*x = PrincipalOrResourceConstraint{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalOrResourceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalOrResourceConstraint) ProtoMessage() {}

func (x *PrincipalOrResourceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalOrResourceConstraint.ProtoReflect.Descriptor instead.
func (*PrincipalOrResourceConstraint) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *PrincipalOrResourceConstraint) GetData() isPrincipalOrResourceConstraint_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PrincipalOrResourceConstraint) GetAny() PrincipalOrResourceConstraint_Any {
	if x != nil {
		if x, ok := x.Data.(*PrincipalOrResourceConstraint_Any_); ok {
			return x.Any
		}
	}
	return PrincipalOrResourceConstraint_unit
}

func (x *PrincipalOrResourceConstraint) GetIn() *PrincipalOrResourceConstraint_InMessage {
	if x != nil {
		if x, ok := x.Data.(*PrincipalOrResourceConstraint_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *PrincipalOrResourceConstraint) GetEq() *PrincipalOrResourceConstraint_EqMessage {
	if x != nil {
		if x, ok := x.Data.(*PrincipalOrResourceConstraint_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

func (x *PrincipalOrResourceConstraint) GetIs() *PrincipalOrResourceConstraint_IsMessage {
	if x != nil {
		if x, ok := x.Data.(*PrincipalOrResourceConstraint_Is); ok {
			return x.Is
		}
	}
	return nil
}

func (x *PrincipalOrResourceConstraint) GetIsIn() *PrincipalOrResourceConstraint_IsInMessage {
	if x != nil {
		if x, ok := x.Data.(*PrincipalOrResourceConstraint_IsIn); ok {
			return x.IsIn
		}
	}
	return nil
}

type isPrincipalOrResourceConstraint_Data interface {
	isPrincipalOrResourceConstraint_Data()
}

type PrincipalOrResourceConstraint_Any_ struct {
	Any PrincipalOrResourceConstraint_Any `protobuf:"varint,1,opt,name=any,proto3,enum=cedar_policy_core.PrincipalOrResourceConstraint_Any,oneof"`
}

type PrincipalOrResourceConstraint_In struct {
	In *PrincipalOrResourceConstraint_InMessage `protobuf:"bytes,2,opt,name=in,proto3,oneof"`
}

type PrincipalOrResourceConstraint_Eq struct {
	Eq *PrincipalOrResourceConstraint_EqMessage `protobuf:"bytes,3,opt,name=eq,proto3,oneof"`
}

type PrincipalOrResourceConstraint_Is struct {
	Is *PrincipalOrResourceConstraint_IsMessage `protobuf:"bytes,4,opt,name=is,proto3,oneof"`
}

type PrincipalOrResourceConstraint_IsIn struct {
	IsIn *PrincipalOrResourceConstraint_IsInMessage `protobuf:"bytes,5,opt,name=isIn,proto3,oneof"`
}

func (*PrincipalOrResourceConstraint_Any_) isPrincipalOrResourceConstraint_Data() {}

func (*PrincipalOrResourceConstraint_In) isPrincipalOrResourceConstraint_Data() {}

func (*PrincipalOrResourceConstraint_Eq) isPrincipalOrResourceConstraint_Data() {}

func (*PrincipalOrResourceConstraint_Is) isPrincipalOrResourceConstraint_Data() {}

func (*PrincipalOrResourceConstraint_IsIn) isPrincipalOrResourceConstraint_Data() {}

type ActionConstraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ActionConstraint_Any_
	//	*ActionConstraint_In
	//	*ActionConstraint_Eq
	Data          isActionConstraint_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionConstraint) Reset() {
	*x = ActionConstraint{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionConstraint) ProtoMessage() {}

func (x *ActionConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionConstraint.ProtoReflect.Descriptor instead.
func (*ActionConstraint) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *ActionConstraint) GetData() isActionConstraint_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ActionConstraint) GetAny() ActionConstraint_Any {
	if x != nil {
		if x, ok := x.Data.(*ActionConstraint_Any_); ok {
			return x.Any
		}
	}
	return ActionConstraint_unit
}

func (x *ActionConstraint) GetIn() *ActionConstraint_InMessage {
	if x != nil {
		if x, ok := x.Data.(*ActionConstraint_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *ActionConstraint) GetEq() *ActionConstraint_EqMessage {
	if x != nil {
		if x, ok := x.Data.(*ActionConstraint_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

type isActionConstraint_Data interface {
	isActionConstraint_Data()
}

type ActionConstraint_Any_ struct {
	Any ActionConstraint_Any `protobuf:"varint,1,opt,name=any,proto3,enum=cedar_policy_core.ActionConstraint_Any,oneof"`
}

type ActionConstraint_In struct {
	In *ActionConstraint_InMessage `protobuf:"bytes,2,opt,name=in,proto3,oneof"`
}

type ActionConstraint_Eq struct {
	Eq *ActionConstraint_EqMessage `protobuf:"bytes,3,opt,name=eq,proto3,oneof"`
}

func (*ActionConstraint_Any_) isActionConstraint_Data() {}

func (*ActionConstraint_In) isActionConstraint_Data() {}

func (*ActionConstraint_Eq) isActionConstraint_Data() {}

type Expr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ExprKind:
	//
	//	*Expr_Lit
	//	*Expr_Var_
	//	*Expr_Slot
	//	*Expr_If_
	//	*Expr_And_
	//	*Expr_Or_
	//	*Expr_UApp
	//	*Expr_BApp
	//	*Expr_ExtApp
	//	*Expr_GetAttr_
	//	*Expr_HasAttr_
	//	*Expr_Like_
	//	*Expr_Is_
	//	*Expr_Set_
	//	*Expr_Record_
	ExprKind      isExpr_ExprKind `protobuf_oneof:"expr_kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr) Reset() {
	*x = Expr{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr) ProtoMessage() {}

func (x *Expr) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr.ProtoReflect.Descriptor instead.
func (*Expr) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *Expr) GetExprKind() isExpr_ExprKind {
	if x != nil {
		return x.ExprKind
	}
	return nil
}

func (x *Expr) GetLit() *Expr_Literal {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Lit); ok {
			return x.Lit
		}
	}
	return nil
}

func (x *Expr) GetVar() Expr_Var {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Var_); ok {
			return x.Var
		}
	}
	return Expr_Principal
}

func (x *Expr) GetSlot() SlotId {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Slot); ok {
			return x.Slot
		}
	}
	return SlotId_Principal
}

func (x *Expr) GetIf() *Expr_If {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_If_); ok {
			return x.If
		}
	}
	return nil
}

func (x *Expr) GetAnd() *Expr_And {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_And_); ok {
			return x.And
		}
	}
	return nil
}

func (x *Expr) GetOr() *Expr_Or {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Or_); ok {
			return x.Or
		}
	}
	return nil
}

func (x *Expr) GetUApp() *Expr_UnaryApp {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_UApp); ok {
			return x.UApp
		}
	}
	return nil
}

func (x *Expr) GetBApp() *Expr_BinaryApp {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_BApp); ok {
			return x.BApp
		}
	}
	return nil
}

func (x *Expr) GetExtApp() *Expr_ExtensionFunctionApp {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_ExtApp); ok {
			return x.ExtApp
		}
	}
	return nil
}

func (x *Expr) GetGetAttr() *Expr_GetAttr {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_GetAttr_); ok {
			return x.GetAttr
		}
	}
	return nil
}

func (x *Expr) GetHasAttr() *Expr_HasAttr {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_HasAttr_); ok {
			return x.HasAttr
		}
	}
	return nil
}

func (x *Expr) GetLike() *Expr_Like {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Like_); ok {
			return x.Like
		}
	}
	return nil
}

func (x *Expr) GetIs() *Expr_Is {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Is_); ok {
			return x.Is
		}
	}
	return nil
}

func (x *Expr) GetSet() *Expr_Set {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Set_); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Expr) GetRecord() *Expr_Record {
	if x != nil {
		if x, ok := x.ExprKind.(*Expr_Record_); ok {
			return x.Record
		}
	}
	return nil
}

type isExpr_ExprKind interface {
	isExpr_ExprKind()
}

type Expr_Lit struct {
	Lit *Expr_Literal `protobuf:"bytes,1,opt,name=lit,proto3,oneof"`
}

type Expr_Var_ struct {
	Var Expr_Var `protobuf:"varint,2,opt,name=var,proto3,enum=cedar_policy_core.Expr_Var,oneof"`
}

type Expr_Slot struct {
	Slot SlotId `protobuf:"varint,3,opt,name=slot,proto3,enum=cedar_policy_core.SlotId,oneof"`
}

type Expr_If_ struct {
	If *Expr_If `protobuf:"bytes,4,opt,name=if,proto3,oneof"`
}

type Expr_And_ struct {
	And *Expr_And `protobuf:"bytes,5,opt,name=and,proto3,oneof"`
}

type Expr_Or_ struct {
	Or *Expr_Or `protobuf:"bytes,6,opt,name=or,proto3,oneof"`
}

type Expr_UApp struct {
	UApp *Expr_UnaryApp `protobuf:"bytes,7,opt,name=uApp,proto3,oneof"`
}

type Expr_BApp struct {
	BApp *Expr_BinaryApp `protobuf:"bytes,8,opt,name=bApp,proto3,oneof"`
}

type Expr_ExtApp struct {
	ExtApp *Expr_ExtensionFunctionApp `protobuf:"bytes,9,opt,name=extApp,proto3,oneof"`
}

type Expr_GetAttr_ struct {
	GetAttr *Expr_GetAttr `protobuf:"bytes,10,opt,name=getAttr,proto3,oneof"`
}

type Expr_HasAttr_ struct {
	HasAttr *Expr_HasAttr `protobuf:"bytes,11,opt,name=hasAttr,proto3,oneof"`
}

type Expr_Like_ struct {
	Like *Expr_Like `protobuf:"bytes,12,opt,name=like,proto3,oneof"`
}

type Expr_Is_ struct {
	Is *Expr_Is `protobuf:"bytes,13,opt,name=is,proto3,oneof"`
}

type Expr_Set_ struct {
	Set *Expr_Set `protobuf:"bytes,14,opt,name=set,proto3,oneof"`
}

type Expr_Record_ struct {
	Record *Expr_Record `protobuf:"bytes,15,opt,name=record,proto3,oneof"`
}

func (*Expr_Lit) isExpr_ExprKind() {}

func (*Expr_Var_) isExpr_ExprKind() {}

func (*Expr_Slot) isExpr_ExprKind() {}

func (*Expr_If_) isExpr_ExprKind() {}

func (*Expr_And_) isExpr_ExprKind() {}

func (*Expr_Or_) isExpr_ExprKind() {}

func (*Expr_UApp) isExpr_ExprKind() {}

func (*Expr_BApp) isExpr_ExprKind() {}

func (*Expr_ExtApp) isExpr_ExprKind() {}

func (*Expr_GetAttr_) isExpr_ExprKind() {}

func (*Expr_HasAttr_) isExpr_ExprKind() {}

func (*Expr_Like_) isExpr_ExprKind() {}

func (*Expr_Is_) isExpr_ExprKind() {}

func (*Expr_Set_) isExpr_ExprKind() {}

func (*Expr_Record_) isExpr_ExprKind() {}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           *EntityUid             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Attrs         map[string]*Expr       `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ancestors     []*EntityUid           `protobuf:"bytes,3,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	Tags          map[string]*Expr       `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *Entity) GetUid() *EntityUid {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *Entity) GetAttrs() map[string]*Expr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Entity) GetAncestors() []*EntityUid {
	if x != nil {
		return x.Ancestors
	}
	return nil
}

func (x *Entity) GetTags() map[string]*Expr {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PrincipalOrResourceConstraint_InMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Er            *EntityReference       `protobuf:"bytes,1,opt,name=er,proto3" json:"er,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalOrResourceConstraint_InMessage) Reset() {
	*x = PrincipalOrResourceConstraint_InMessage{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalOrResourceConstraint_InMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalOrResourceConstraint_InMessage) ProtoMessage() {}

func (x *PrincipalOrResourceConstraint_InMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalOrResourceConstraint_InMessage.ProtoReflect.Descriptor instead.
func (*PrincipalOrResourceConstraint_InMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8, 0}
}

func (x *PrincipalOrResourceConstraint_InMessage) GetEr() *EntityReference {
	if x != nil {
		return x.Er
	}
	return nil
}

type PrincipalOrResourceConstraint_EqMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Er            *EntityReference       `protobuf:"bytes,1,opt,name=er,proto3" json:"er,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalOrResourceConstraint_EqMessage) Reset() {
	*x = PrincipalOrResourceConstraint_EqMessage{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalOrResourceConstraint_EqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalOrResourceConstraint_EqMessage) ProtoMessage() {}

func (x *PrincipalOrResourceConstraint_EqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalOrResourceConstraint_EqMessage.ProtoReflect.Descriptor instead.
func (*PrincipalOrResourceConstraint_EqMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8, 1}
}

func (x *PrincipalOrResourceConstraint_EqMessage) GetEr() *EntityReference {
	if x != nil {
		return x.Er
	}
	return nil
}

type PrincipalOrResourceConstraint_IsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    *Name                  `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalOrResourceConstraint_IsMessage) Reset() {
	*x = PrincipalOrResourceConstraint_IsMessage{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalOrResourceConstraint_IsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalOrResourceConstraint_IsMessage) ProtoMessage() {}

func (x *PrincipalOrResourceConstraint_IsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalOrResourceConstraint_IsMessage.ProtoReflect.Descriptor instead.
func (*PrincipalOrResourceConstraint_IsMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8, 2}
}

func (x *PrincipalOrResourceConstraint_IsMessage) GetEntityType() *Name {
	if x != nil {
		return x.EntityType
	}
	return nil
}

type PrincipalOrResourceConstraint_IsInMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Er            *EntityReference       `protobuf:"bytes,1,opt,name=er,proto3" json:"er,omitempty"`
	EntityType    *Name                  `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalOrResourceConstraint_IsInMessage) Reset() {
	*x = PrincipalOrResourceConstraint_IsInMessage{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalOrResourceConstraint_IsInMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalOrResourceConstraint_IsInMessage) ProtoMessage() {}

func (x *PrincipalOrResourceConstraint_IsInMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalOrResourceConstraint_IsInMessage.ProtoReflect.Descriptor instead.
func (*PrincipalOrResourceConstraint_IsInMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8, 3}
}

func (x *PrincipalOrResourceConstraint_IsInMessage) GetEr() *EntityReference {
	if x != nil {
		return x.Er
	}
	return nil
}

func (x *PrincipalOrResourceConstraint_IsInMessage) GetEntityType() *Name {
	if x != nil {
		return x.EntityType
	}
	return nil
}

type ActionConstraint_InMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Euids         []*EntityUid           `protobuf:"bytes,1,rep,name=euids,proto3" json:"euids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionConstraint_InMessage) Reset() {
	*x = ActionConstraint_InMessage{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionConstraint_InMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionConstraint_InMessage) ProtoMessage() {}

func (x *ActionConstraint_InMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionConstraint_InMessage.ProtoReflect.Descriptor instead.
func (*ActionConstraint_InMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ActionConstraint_InMessage) GetEuids() []*EntityUid {
	if x != nil {
		return x.Euids
	}
	return nil
}

type ActionConstraint_EqMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Euid          *EntityUid             `protobuf:"bytes,1,opt,name=euid,proto3" json:"euid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionConstraint_EqMessage) Reset() {
	*x = ActionConstraint_EqMessage{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionConstraint_EqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionConstraint_EqMessage) ProtoMessage() {}

func (x *ActionConstraint_EqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionConstraint_EqMessage.ProtoReflect.Descriptor instead.
func (*ActionConstraint_EqMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9, 1}
}

func (x *ActionConstraint_EqMessage) GetEuid() *EntityUid {
	if x != nil {
		return x.Euid
	}
	return nil
}

type Expr_Literal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lit:
	//
	//	*Expr_Literal_B
	//	*Expr_Literal_I
	//	*Expr_Literal_S
	//	*Expr_Literal_Euid
	Lit           isExpr_Literal_Lit `protobuf_oneof:"lit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Literal) Reset() {
	*x = Expr_Literal{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Literal) ProtoMessage() {}

func (x *Expr_Literal) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Literal.ProtoReflect.Descriptor instead.
func (*Expr_Literal) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Expr_Literal) GetLit() isExpr_Literal_Lit {
	if x != nil {
		return x.Lit
	}
	return nil
}

func (x *Expr_Literal) GetB() bool {
	if x != nil {
		if x, ok := x.Lit.(*Expr_Literal_B); ok {
			return x.B
		}
	}
	return false
}

func (x *Expr_Literal) GetI() int64 {
	if x != nil {
		if x, ok := x.Lit.(*Expr_Literal_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *Expr_Literal) GetS() string {
	if x != nil {
		if x, ok := x.Lit.(*Expr_Literal_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *Expr_Literal) GetEuid() *EntityUid {
	if x != nil {
		if x, ok := x.Lit.(*Expr_Literal_Euid); ok {
			return x.Euid
		}
	}
	return nil
}

type isExpr_Literal_Lit interface {
	isExpr_Literal_Lit()
}

type Expr_Literal_B struct {
	B bool `protobuf:"varint,1,opt,name=b,proto3,oneof"`
}

type Expr_Literal_I struct {
	I int64 `protobuf:"varint,2,opt,name=i,proto3,oneof"`
}

type Expr_Literal_S struct {
	S string `protobuf:"bytes,3,opt,name=s,proto3,oneof"`
}

type Expr_Literal_Euid struct {
	Euid *EntityUid `protobuf:"bytes,4,opt,name=euid,proto3,oneof"`
}

func (*Expr_Literal_B) isExpr_Literal_Lit() {}

func (*Expr_Literal_I) isExpr_Literal_Lit() {}

func (*Expr_Literal_S) isExpr_Literal_Lit() {}

func (*Expr_Literal_Euid) isExpr_Literal_Lit() {}

type Expr_If struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestExpr      *Expr                  `protobuf:"bytes,1,opt,name=test_expr,json=testExpr,proto3" json:"test_expr,omitempty"`
	ThenExpr      *Expr                  `protobuf:"bytes,2,opt,name=then_expr,json=thenExpr,proto3" json:"then_expr,omitempty"`
	ElseExpr      *Expr                  `protobuf:"bytes,3,opt,name=else_expr,json=elseExpr,proto3" json:"else_expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_If) Reset() {
	*x = Expr_If{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_If) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_If) ProtoMessage() {}

func (x *Expr_If) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_If.ProtoReflect.Descriptor instead.
func (*Expr_If) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 1}
}

func (x *Expr_If) GetTestExpr() *Expr {
	if x != nil {
		return x.TestExpr
	}
	return nil
}

func (x *Expr_If) GetThenExpr() *Expr {
	if x != nil {
		return x.ThenExpr
	}
	return nil
}

func (x *Expr_If) GetElseExpr() *Expr {
	if x != nil {
		return x.ElseExpr
	}
	return nil
}

type Expr_And struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Expr                  `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Expr                  `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_And) Reset() {
	*x = Expr_And{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_And) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_And) ProtoMessage() {}

func (x *Expr_And) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_And.ProtoReflect.Descriptor instead.
func (*Expr_And) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 2}
}

func (x *Expr_And) GetLeft() *Expr {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Expr_And) GetRight() *Expr {
	if x != nil {
		return x.Right
	}
	return nil
}

type Expr_Or struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Expr                  `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Expr                  `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Or) Reset() {
	*x = Expr_Or{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Or) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Or) ProtoMessage() {}

func (x *Expr_Or) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Or.ProtoReflect.Descriptor instead.
func (*Expr_Or) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 3}
}

func (x *Expr_Or) GetLeft() *Expr {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Expr_Or) GetRight() *Expr {
	if x != nil {
		return x.Right
	}
	return nil
}

type Expr_UnaryApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Expr_UnaryApp_Op       `protobuf:"varint,1,opt,name=op,proto3,enum=cedar_policy_core.Expr_UnaryApp_Op" json:"op,omitempty"`
	Expr          *Expr                  `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_UnaryApp) Reset() {
	*x = Expr_UnaryApp{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_UnaryApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_UnaryApp) ProtoMessage() {}

func (x *Expr_UnaryApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_UnaryApp.ProtoReflect.Descriptor instead.
func (*Expr_UnaryApp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 4}
}

func (x *Expr_UnaryApp) GetOp() Expr_UnaryApp_Op {
	if x != nil {
		return x.Op
	}
	return Expr_UnaryApp_Not
}

func (x *Expr_UnaryApp) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

type Expr_BinaryApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Expr_BinaryApp_Op      `protobuf:"varint,1,opt,name=op,proto3,enum=cedar_policy_core.Expr_BinaryApp_Op" json:"op,omitempty"`
	Left          *Expr                  `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Expr                  `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_BinaryApp) Reset() {
	*x = Expr_BinaryApp{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_BinaryApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_BinaryApp) ProtoMessage() {}

func (x *Expr_BinaryApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_BinaryApp.ProtoReflect.Descriptor instead.
func (*Expr_BinaryApp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 5}
}

func (x *Expr_BinaryApp) GetOp() Expr_BinaryApp_Op {
	if x != nil {
		return x.Op
	}
	return Expr_BinaryApp_Eq
}

func (x *Expr_BinaryApp) GetLeft() *Expr {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Expr_BinaryApp) GetRight() *Expr {
	if x != nil {
		return x.Right
	}
	return nil
}

type Expr_ExtensionFunctionApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FnName        *Name                  `protobuf:"bytes,1,opt,name=fn_name,json=fnName,proto3" json:"fn_name,omitempty"`
	Args          []*Expr                `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_ExtensionFunctionApp) Reset() {
	*x = Expr_ExtensionFunctionApp{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_ExtensionFunctionApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_ExtensionFunctionApp) ProtoMessage() {}

func (x *Expr_ExtensionFunctionApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_ExtensionFunctionApp.ProtoReflect.Descriptor instead.
func (*Expr_ExtensionFunctionApp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 6}
}

func (x *Expr_ExtensionFunctionApp) GetFnName() *Name {
	if x != nil {
		return x.FnName
	}
	return nil
}

func (x *Expr_ExtensionFunctionApp) GetArgs() []*Expr {
	if x != nil {
		return x.Args
	}
	return nil
}

type Expr_GetAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Attr          string                 `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_GetAttr) Reset() {
	*x = Expr_GetAttr{}
	mi := &file_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_GetAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_GetAttr) ProtoMessage() {}

func (x *Expr_GetAttr) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_GetAttr.ProtoReflect.Descriptor instead.
func (*Expr_GetAttr) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 7}
}

func (x *Expr_GetAttr) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Expr_GetAttr) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type Expr_HasAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Attr          string                 `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_HasAttr) Reset() {
	*x = Expr_HasAttr{}
	mi := &file_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_HasAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_HasAttr) ProtoMessage() {}

func (x *Expr_HasAttr) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_HasAttr.ProtoReflect.Descriptor instead.
func (*Expr_HasAttr) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 8}
}

func (x *Expr_HasAttr) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Expr_HasAttr) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type Expr_Like struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Expr          *Expr                    `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Pattern       []*Expr_Like_PatternElem `protobuf:"bytes,2,rep,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Like) Reset() {
	*x = Expr_Like{}
	mi := &file_core_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Like) ProtoMessage() {}

func (x *Expr_Like) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Like.ProtoReflect.Descriptor instead.
func (*Expr_Like) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 9}
}

func (x *Expr_Like) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Expr_Like) GetPattern() []*Expr_Like_PatternElem {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type Expr_Is struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	EntityType    *Name                  `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Is) Reset() {
	*x = Expr_Is{}
	mi := &file_core_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Is) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Is) ProtoMessage() {}

func (x *Expr_Is) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Is.ProtoReflect.Descriptor instead.
func (*Expr_Is) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 10}
}

func (x *Expr_Is) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Expr_Is) GetEntityType() *Name {
	if x != nil {
		return x.EntityType
	}
	return nil
}

type Expr_Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Expr                `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Set) Reset() {
	*x = Expr_Set{}
	mi := &file_core_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Set) ProtoMessage() {}

func (x *Expr_Set) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Set.ProtoReflect.Descriptor instead.
func (*Expr_Set) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 11}
}

func (x *Expr_Set) GetElements() []*Expr {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Expr_Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*Expr       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Record) Reset() {
	*x = Expr_Record{}
	mi := &file_core_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Record) ProtoMessage() {}

func (x *Expr_Record) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Record.ProtoReflect.Descriptor instead.
func (*Expr_Record) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 12}
}

func (x *Expr_Record) GetItems() map[string]*Expr {
	if x != nil {
		return x.Items
	}
	return nil
}

type Expr_Like_PatternElem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Expr_Like_PatternElem_Wildcard_
	//	*Expr_Like_PatternElem_C
	Data          isExpr_Like_PatternElem_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr_Like_PatternElem) Reset() {
	*x = Expr_Like_PatternElem{}
	mi := &file_core_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr_Like_PatternElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr_Like_PatternElem) ProtoMessage() {}

func (x *Expr_Like_PatternElem) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr_Like_PatternElem.ProtoReflect.Descriptor instead.
func (*Expr_Like_PatternElem) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10, 9, 0}
}

func (x *Expr_Like_PatternElem) GetData() isExpr_Like_PatternElem_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Expr_Like_PatternElem) GetWildcard() Expr_Like_PatternElem_Wildcard {
	if x != nil {
		if x, ok := x.Data.(*Expr_Like_PatternElem_Wildcard_); ok {
			return x.Wildcard
		}
	}
	return Expr_Like_PatternElem_unit
}

func (x *Expr_Like_PatternElem) GetC() string {
	if x != nil {
		if x, ok := x.Data.(*Expr_Like_PatternElem_C); ok {
			return x.C
		}
	}
	return ""
}

type isExpr_Like_PatternElem_Data interface {
	isExpr_Like_PatternElem_Data()
}

type Expr_Like_PatternElem_Wildcard_ struct {
	Wildcard Expr_Like_PatternElem_Wildcard `protobuf:"varint,1,opt,name=wildcard,proto3,enum=cedar_policy_core.Expr_Like_PatternElem_Wildcard,oneof"`
}

type Expr_Like_PatternElem_C struct {
	C string `protobuf:"bytes,2,opt,name=c,proto3,oneof"`
}

func (*Expr_Like_PatternElem_Wildcard_) isExpr_Like_PatternElem_Data() {}

func (*Expr_Like_PatternElem_C) isExpr_Like_PatternElem_Data() {}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x11cedar_policy_core\"\xcd\x02\n" +
	"\aRequest\x12:\n" +
	"\tprincipal\x18\x01 \x01(\v2\x1c.cedar_policy_core.EntityUidR\tprincipal\x124\n" +
	"\x06action\x18\x02 \x01(\v2\x1c.cedar_policy_core.EntityUidR\x06action\x128\n" +
	"\bresource\x18\x03 \x01(\v2\x1c.cedar_policy_core.EntityUidR\bresource\x12A\n" +
	"\acontext\x18\x04 \x03(\v2'.cedar_policy_core.Request.ContextEntryR\acontext\x1aS\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x05value:\x028\x01\"{\n" +
	"\tPolicySet\x12=\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1f.cedar_policy_core.TemplateBodyR\ttemplates\x12/\n" +
	"\x05links\x18\x02 \x03(\v2\x19.cedar_policy_core.PolicyR\x05links\"A\n" +
	"\bEntities\x125\n" +
	"\bentities\x18\x01 \x03(\v2\x19.cedar_policy_core.EntityR\bentities\"F\n" +
	"\tEntityUid\x12'\n" +
	"\x02ty\x18\x01 \x01(\v2\x17.cedar_policy_core.NameR\x02ty\x12\x10\n" +
	"\x03eid\x18\x02 \x01(\tR\x03eid\"*\n" +
	"\x04Name\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x03(\tR\x04path\"\x85\x02\n" +
	"\x06Policy\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1c\n" +
	"\alink_id\x18\x02 \x01(\tH\x00R\x06linkId\x88\x01\x01\x12(\n" +
	"\x10is_template_link\x18\x03 \x01(\bR\x0eisTemplateLink\x12C\n" +
	"\x0eprincipal_euid\x18\x04 \x01(\v2\x1c.cedar_policy_core.EntityUidR\rprincipalEuid\x12A\n" +
	"\rresource_euid\x18\x05 \x01(\v2\x1c.cedar_policy_core.EntityUidR\fresourceEuidB\n" +
	"\n" +
	"\b_link_id\"\xcc\x04\n" +
	"\fTemplateBody\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12R\n" +
	"\vannotations\x18\x03 \x03(\v20.cedar_policy_core.TemplateBody.AnnotationsEntryR\vannotations\x121\n" +
	"\x06effect\x18\x04 \x01(\x0e2\x19.cedar_policy_core.EffectR\x06effect\x12c\n" +
	"\x14principal_constraint\x18\x05 \x01(\v20.cedar_policy_core.PrincipalOrResourceConstraintR\x13principalConstraint\x12P\n" +
	"\x11action_constraint\x18\x06 \x01(\v2#.cedar_policy_core.ActionConstraintR\x10actionConstraint\x12a\n" +
	"\x13resource_constraint\x18\a \x01(\v20.cedar_policy_core.PrincipalOrResourceConstraintR\x12resourceConstraint\x12K\n" +
	"\x15non_scope_constraints\x18\b \x01(\v2\x17.cedar_policy_core.ExprR\x13nonScopeConstraints\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x0fEntityReference\x12=\n" +
	"\x04slot\x18\x01 \x01(\x0e2'.cedar_policy_core.EntityReference.SlotH\x00R\x04slot\x122\n" +
	"\x04euid\x18\x02 \x01(\v2\x1c.cedar_policy_core.EntityUidH\x00R\x04euid\"\x10\n" +
	"\x04Slot\x12\b\n" +
	"\x04unit\x10\x00B\x06\n" +
	"\x04data\"\x86\x06\n" +
	"\x1dPrincipalOrResourceConstraint\x12H\n" +
	"\x03any\x18\x01 \x01(\x0e24.cedar_policy_core.PrincipalOrResourceConstraint.AnyH\x00R\x03any\x12L\n" +
	"\x02in\x18\x02 \x01(\v2:.cedar_policy_core.PrincipalOrResourceConstraint.InMessageH\x00R\x02in\x12L\n" +
	"\x02eq\x18\x03 \x01(\v2:.cedar_policy_core.PrincipalOrResourceConstraint.EqMessageH\x00R\x02eq\x12L\n" +
	"\x02is\x18\x04 \x01(\v2:.cedar_policy_core.PrincipalOrResourceConstraint.IsMessageH\x00R\x02is\x12R\n" +
	"\x04isIn\x18\x05 \x01(\v2<.cedar_policy_core.PrincipalOrResourceConstraint.IsInMessageH\x00R\x04isIn\x1a?\n" +
	"\tInMessage\x122\n" +
	"\x02er\x18\x01 \x01(\v2\".cedar_policy_core.EntityReferenceR\x02er\x1a?\n" +
	"\tEqMessage\x122\n" +
	"\x02er\x18\x01 \x01(\v2\".cedar_policy_core.EntityReferenceR\x02er\x1aE\n" +
	"\tIsMessage\x128\n" +
	"\ventity_type\x18\x01 \x01(\v2\x17.cedar_policy_core.NameR\n" +
	"entityType\x1a{\n" +
	"\vIsInMessage\x122\n" +
	"\x02er\x18\x01 \x01(\v2\".cedar_policy_core.EntityReferenceR\x02er\x128\n" +
	"\ventity_type\x18\x02 \x01(\v2\x17.cedar_policy_core.NameR\n" +
	"entityType\"\x0f\n" +
	"\x03Any\x12\b\n" +
	"\x04unit\x10\x00B\x06\n" +
	"\x04data\"\xea\x02\n" +
	"\x10ActionConstraint\x12;\n" +
	"\x03any\x18\x01 \x01(\x0e2'.cedar_policy_core.ActionConstraint.AnyH\x00R\x03any\x12?\n" +
	"\x02in\x18\x02 \x01(\v2-.cedar_policy_core.ActionConstraint.InMessageH\x00R\x02in\x12?\n" +
	"\x02eq\x18\x03 \x01(\v2-.cedar_policy_core.ActionConstraint.EqMessageH\x00R\x02eq\x1a?\n" +
	"\tInMessage\x122\n" +
	"\x05euids\x18\x01 \x03(\v2\x1c.cedar_policy_core.EntityUidR\x05euids\x1a=\n" +
	"\tEqMessage\x120\n" +
	"\x04euid\x18\x01 \x01(\v2\x1c.cedar_policy_core.EntityUidR\x04euid\"\x0f\n" +
	"\x03Any\x12\b\n" +
	"\x04unit\x10\x00B\x06\n" +
	"\x04data\"\xfc\x14\n" +
	"\x04Expr\x123\n" +
	"\x03lit\x18\x01 \x01(\v2\x1f.cedar_policy_core.Expr.LiteralH\x00R\x03lit\x12/\n" +
	"\x03var\x18\x02 \x01(\x0e2\x1b.cedar_policy_core.Expr.VarH\x00R\x03var\x12/\n" +
	"\x04slot\x18\x03 \x01(\x0e2\x19.cedar_policy_core.SlotIdH\x00R\x04slot\x12,\n" +
	"\x02if\x18\x04 \x01(\v2\x1a.cedar_policy_core.Expr.IfH\x00R\x02if\x12/\n" +
	"\x03and\x18\x05 \x01(\v2\x1b.cedar_policy_core.Expr.AndH\x00R\x03and\x12,\n" +
	"\x02or\x18\x06 \x01(\v2\x1a.cedar_policy_core.Expr.OrH\x00R\x02or\x126\n" +
	"\x04uApp\x18\a \x01(\v2 .cedar_policy_core.Expr.UnaryAppH\x00R\x04uApp\x127\n" +
	"\x04bApp\x18\b \x01(\v2!.cedar_policy_core.Expr.BinaryAppH\x00R\x04bApp\x12F\n" +
	"\x06extApp\x18\t \x01(\v2,.cedar_policy_core.Expr.ExtensionFunctionAppH\x00R\x06extApp\x12;\n" +
	"\agetAttr\x18\n" +
	" \x01(\v2\x1f.cedar_policy_core.Expr.GetAttrH\x00R\agetAttr\x12;\n" +
	"\ahasAttr\x18\v \x01(\v2\x1f.cedar_policy_core.Expr.HasAttrH\x00R\ahasAttr\x122\n" +
	"\x04like\x18\f \x01(\v2\x1c.cedar_policy_core.Expr.LikeH\x00R\x04like\x12,\n" +
	"\x02is\x18\r \x01(\v2\x1a.cedar_policy_core.Expr.IsH\x00R\x02is\x12/\n" +
	"\x03set\x18\x0e \x01(\v2\x1b.cedar_policy_core.Expr.SetH\x00R\x03set\x128\n" +
	"\x06record\x18\x0f \x01(\v2\x1e.cedar_policy_core.Expr.RecordH\x00R\x06record\x1at\n" +
	"\aLiteral\x12\x0e\n" +
	"\x01b\x18\x01 \x01(\bH\x00R\x01b\x12\x0e\n" +
	"\x01i\x18\x02 \x01(\x03H\x00R\x01i\x12\x0e\n" +
	"\x01s\x18\x03 \x01(\tH\x00R\x01s\x122\n" +
	"\x04euid\x18\x04 \x01(\v2\x1c.cedar_policy_core.EntityUidH\x00R\x04euidB\x05\n" +
	"\x03lit\x1a\xa6\x01\n" +
	"\x02If\x124\n" +
	"\ttest_expr\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\btestExpr\x124\n" +
	"\tthen_expr\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\bthenExpr\x124\n" +
	"\telse_expr\x18\x03 \x01(\v2\x17.cedar_policy_core.ExprR\belseExpr\x1aa\n" +
	"\x03And\x12+\n" +
	"\x04left\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04left\x12-\n" +
	"\x05right\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x05right\x1a`\n" +
	"\x02Or\x12+\n" +
	"\x04left\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04left\x12-\n" +
	"\x05right\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x05right\x1a\x91\x01\n" +
	"\bUnaryApp\x123\n" +
	"\x02op\x18\x01 \x01(\x0e2#.cedar_policy_core.Expr.UnaryApp.OpR\x02op\x12+\n" +
	"\x04expr\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x04expr\"#\n" +
	"\x02Op\x12\a\n" +
	"\x03Not\x10\x00\x12\a\n" +
	"\x03Neg\x10\x01\x12\v\n" +
	"\aIsEmpty\x10\x02\x1a\xad\x02\n" +
	"\tBinaryApp\x124\n" +
	"\x02op\x18\x01 \x01(\x0e2$.cedar_policy_core.Expr.BinaryApp.OpR\x02op\x12+\n" +
	"\x04left\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x04left\x12-\n" +
	"\x05right\x18\x03 \x01(\v2\x17.cedar_policy_core.ExprR\x05right\"\x8d\x01\n" +
	"\x02Op\x12\x06\n" +
	"\x02Eq\x10\x00\x12\b\n" +
	"\x04Less\x10\x01\x12\n" +
	"\n" +
	"\x06LessEq\x10\x02\x12\a\n" +
	"\x03Add\x10\x03\x12\a\n" +
	"\x03Sub\x10\x04\x12\a\n" +
	"\x03Mul\x10\x05\x12\x06\n" +
	"\x02In\x10\x06\x12\f\n" +
	"\bContains\x10\a\x12\x0f\n" +
	"\vContainsAll\x10\b\x12\x0f\n" +
	"\vContainsAny\x10\t\x12\n" +
	"\n" +
	"\x06GetTag\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06HasTag\x10\v\x1au\n" +
	"\x14ExtensionFunctionApp\x120\n" +
	"\afn_name\x18\x01 \x01(\v2\x17.cedar_policy_core.NameR\x06fnName\x12+\n" +
	"\x04args\x18\x02 \x03(\v2\x17.cedar_policy_core.ExprR\x04args\x1aJ\n" +
	"\aGetAttr\x12+\n" +
	"\x04expr\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04expr\x12\x12\n" +
	"\x04attr\x18\x02 \x01(\tR\x04attr\x1aJ\n" +
	"\aHasAttr\x12+\n" +
	"\x04expr\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04expr\x12\x12\n" +
	"\x04attr\x18\x02 \x01(\tR\x04attr\x1a\x86\x02\n" +
	"\x04Like\x12+\n" +
	"\x04expr\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04expr\x12B\n" +
	"\apattern\x18\x02 \x03(\v2(.cedar_policy_core.Expr.Like.PatternElemR\apattern\x1a\x8c\x01\n" +
	"\vPatternElem\x12O\n" +
	"\bwildcard\x18\x01 \x01(\x0e21.cedar_policy_core.Expr.Like.PatternElem.WildcardH\x00R\bwildcard\x12\x0e\n" +
	"\x01c\x18\x02 \x01(\tH\x00R\x01c\"\x14\n" +
	"\bWildcard\x12\b\n" +
	"\x04unit\x10\x00B\x06\n" +
	"\x04data\x1ak\n" +
	"\x02Is\x12+\n" +
	"\x04expr\x18\x01 \x01(\v2\x17.cedar_policy_core.ExprR\x04expr\x128\n" +
	"\ventity_type\x18\x02 \x01(\v2\x17.cedar_policy_core.NameR\n" +
	"entityType\x1a:\n" +
	"\x03Set\x123\n" +
	"\belements\x18\x01 \x03(\v2\x17.cedar_policy_core.ExprR\belements\x1a\x9c\x01\n" +
	"\x06Record\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).cedar_policy_core.Expr.Record.ItemsEntryR\x05items\x1aQ\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x05value:\x028\x01\";\n" +
	"\x03Var\x12\r\n" +
	"\tPrincipal\x10\x00\x12\n" +
	"\n" +
	"\x06Action\x10\x01\x12\f\n" +
	"\bResource\x10\x02\x12\v\n" +
	"\aContext\x10\x03B\v\n" +
	"\texpr_kind\"\x8e\x03\n" +
	"\x06Entity\x12.\n" +
	"\x03uid\x18\x01 \x01(\v2\x1c.cedar_policy_core.EntityUidR\x03uid\x12:\n" +
	"\x05attrs\x18\x02 \x03(\v2$.cedar_policy_core.Entity.AttrsEntryR\x05attrs\x12:\n" +
	"\tancestors\x18\x03 \x03(\v2\x1c.cedar_policy_core.EntityUidR\tancestors\x127\n" +
	"\x04tags\x18\x04 \x03(\v2#.cedar_policy_core.Entity.TagsEntryR\x04tags\x1aQ\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x05value:\x028\x01\x1aP\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.cedar_policy_core.ExprR\x05value:\x028\x01* \n" +
	"\x06Effect\x12\n" +
	"\n" +
	"\x06Forbid\x10\x00\x12\n" +
	"\n" +
	"\x06Permit\x10\x01*%\n" +
	"\x06SlotId\x12\r\n" +
	"\tPrincipal\x10\x00\x12\f\n" +
	"\bResource\x10\x01b\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_core_proto_goTypes = []any{
	(Effect)(0),                            // 0: cedar_policy_core.Effect
	(SlotId)(0),                            // 1: cedar_policy_core.SlotId
	(EntityReference_Slot)(0),              // 2: cedar_policy_core.EntityReference.Slot
	(PrincipalOrResourceConstraint_Any)(0), // 3: cedar_policy_core.PrincipalOrResourceConstraint.Any
	(ActionConstraint_Any)(0),              // 4: cedar_policy_core.ActionConstraint.Any
	(Expr_Var)(0),                          // 5: cedar_policy_core.Expr.Var
	(Expr_UnaryApp_Op)(0),                  // 6: cedar_policy_core.Expr.UnaryApp.Op
	(Expr_BinaryApp_Op)(0),                 // 7: cedar_policy_core.Expr.BinaryApp.Op
	(Expr_Like_PatternElem_Wildcard)(0),    // 8: cedar_policy_core.Expr.Like.PatternElem.Wildcard
	(*Request)(nil),                        // 9: cedar_policy_core.Request
	(*PolicySet)(nil),                      // 10: cedar_policy_core.PolicySet
	(*Entities)(nil),                       // 11: cedar_policy_core.Entities
	(*EntityUid)(nil),                      // 12: cedar_policy_core.EntityUid
	(*Name)(nil),                           // 13: cedar_policy_core.Name
	(*Policy)(nil),                         // 14: cedar_policy_core.Policy
	(*TemplateBody)(nil),                   // 15: cedar_policy_core.TemplateBody
	(*EntityReference)(nil),                // 16: cedar_policy_core.EntityReference
	(*PrincipalOrResourceConstraint)(nil),  // 17: cedar_policy_core.PrincipalOrResourceConstraint
	(*ActionConstraint)(nil),               // 18: cedar_policy_core.ActionConstraint
	(*Expr)(nil),                           // 19: cedar_policy_core.Expr
	(*Entity)(nil),                         // 20: cedar_policy_core.Entity
	nil,                                    // 21: cedar_policy_core.Request.ContextEntry
	nil,                                    // 22: cedar_policy_core.TemplateBody.AnnotationsEntry
	(*PrincipalOrResourceConstraint_InMessage)(nil),   // 23: cedar_policy_core.PrincipalOrResourceConstraint.InMessage
	(*PrincipalOrResourceConstraint_EqMessage)(nil),   // 24: cedar_policy_core.PrincipalOrResourceConstraint.EqMessage
	(*PrincipalOrResourceConstraint_IsMessage)(nil),   // 25: cedar_policy_core.PrincipalOrResourceConstraint.IsMessage
	(*PrincipalOrResourceConstraint_IsInMessage)(nil), // 26: cedar_policy_core.PrincipalOrResourceConstraint.IsInMessage
	(*ActionConstraint_InMessage)(nil),                // 27: cedar_policy_core.ActionConstraint.InMessage
	(*ActionConstraint_EqMessage)(nil),                // 28: cedar_policy_core.ActionConstraint.EqMessage
	(*Expr_Literal)(nil),                              // 29: cedar_policy_core.Expr.Literal
	(*Expr_If)(nil),                                   // 30: cedar_policy_core.Expr.If
	(*Expr_And)(nil),                                  // 31: cedar_policy_core.Expr.And
	(*Expr_Or)(nil),                                   // 32: cedar_policy_core.Expr.Or
	(*Expr_UnaryApp)(nil),                             // 33: cedar_policy_core.Expr.UnaryApp
	(*Expr_BinaryApp)(nil),                            // 34: cedar_policy_core.Expr.BinaryApp
	(*Expr_ExtensionFunctionApp)(nil),                 // 35: cedar_policy_core.Expr.ExtensionFunctionApp
	(*Expr_GetAttr)(nil),                              // 36: cedar_policy_core.Expr.GetAttr
	(*Expr_HasAttr)(nil),                              // 37: cedar_policy_core.Expr.HasAttr
	(*Expr_Like)(nil),                                 // 38: cedar_policy_core.Expr.Like
	(*Expr_Is)(nil),                                   // 39: cedar_policy_core.Expr.Is
	(*Expr_Set)(nil),                                  // 40: cedar_policy_core.Expr.Set
	(*Expr_Record)(nil),                               // 41: cedar_policy_core.Expr.Record
	(*Expr_Like_PatternElem)(nil),                     // 42: cedar_policy_core.Expr.Like.PatternElem
	nil,                                               // 43: cedar_policy_core.Expr.Record.ItemsEntry
	nil,                                               // 44: cedar_policy_core.Entity.AttrsEntry
	nil,                                               // 45: cedar_policy_core.Entity.TagsEntry
}
var file_core_proto_depIdxs = []int32{
	12, // 0: cedar_policy_core.Request.principal:type_name -> cedar_policy_core.EntityUid
	12, // 1: cedar_policy_core.Request.action:type_name -> cedar_policy_core.EntityUid
	12, // 2: cedar_policy_core.Request.resource:type_name -> cedar_policy_core.EntityUid
	21, // 3: cedar_policy_core.Request.context:type_name -> cedar_policy_core.Request.ContextEntry
	15, // 4: cedar_policy_core.PolicySet.templates:type_name -> cedar_policy_core.TemplateBody
	14, // 5: cedar_policy_core.PolicySet.links:type_name -> cedar_policy_core.Policy
	20, // 6: cedar_policy_core.Entities.entities:type_name -> cedar_policy_core.Entity
	13, // 7: cedar_policy_core.EntityUid.ty:type_name -> cedar_policy_core.Name
	12, // 8: cedar_policy_core.Policy.principal_euid:type_name -> cedar_policy_core.EntityUid
	12, // 9: cedar_policy_core.Policy.resource_euid:type_name -> cedar_policy_core.EntityUid
	22, // 10: cedar_policy_core.TemplateBody.annotations:type_name -> cedar_policy_core.TemplateBody.AnnotationsEntry
	0,  // 11: cedar_policy_core.TemplateBody.effect:type_name -> cedar_policy_core.Effect
	17, // 12: cedar_policy_core.TemplateBody.principal_constraint:type_name -> cedar_policy_core.PrincipalOrResourceConstraint
	18, // 13: cedar_policy_core.TemplateBody.action_constraint:type_name -> cedar_policy_core.ActionConstraint
	17, // 14: cedar_policy_core.TemplateBody.resource_constraint:type_name -> cedar_policy_core.PrincipalOrResourceConstraint
	19, // 15: cedar_policy_core.TemplateBody.non_scope_constraints:type_name -> cedar_policy_core.Expr
	2,  // 16: cedar_policy_core.EntityReference.slot:type_name -> cedar_policy_core.EntityReference.Slot
	12, // 17: cedar_policy_core.EntityReference.euid:type_name -> cedar_policy_core.EntityUid
	3,  // 18: cedar_policy_core.PrincipalOrResourceConstraint.any:type_name -> cedar_policy_core.PrincipalOrResourceConstraint.Any
	23, // 19: cedar_policy_core.PrincipalOrResourceConstraint.in:type_name -> cedar_policy_core.PrincipalOrResourceConstraint.InMessage
	24, // 20: cedar_policy_core.PrincipalOrResourceConstraint.eq:type_name -> cedar_policy_core.PrincipalOrResourceConstraint.EqMessage
	25, // 21: cedar_policy_core.PrincipalOrResourceConstraint.is:type_name -> cedar_policy_core.PrincipalOrResourceConstraint.IsMessage
	26, // 22: cedar_policy_core.PrincipalOrResourceConstraint.isIn:type_name -> cedar_policy_core.PrincipalOrResourceConstraint.IsInMessage
	4,  // 23: cedar_policy_core.ActionConstraint.any:type_name -> cedar_policy_core.ActionConstraint.Any
	27, // 24: cedar_policy_core.ActionConstraint.in:type_name -> cedar_policy_core.ActionConstraint.InMessage
	28, // 25: cedar_policy_core.ActionConstraint.eq:type_name -> cedar_policy_core.ActionConstraint.EqMessage
	29, // 26: cedar_policy_core.Expr.lit:type_name -> cedar_policy_core.Expr.Literal
	5,  // 27: cedar_policy_core.Expr.var:type_name -> cedar_policy_core.Expr.Var
	1,  // 28: cedar_policy_core.Expr.slot:type_name -> cedar_policy_core.SlotId
	30, // 29: cedar_policy_core.Expr.if:type_name -> cedar_policy_core.Expr.If
	31, // 30: cedar_policy_core.Expr.and:type_name -> cedar_policy_core.Expr.And
	32, // 31: cedar_policy_core.Expr.or:type_name -> cedar_policy_core.Expr.Or
	33, // 32: cedar_policy_core.Expr.uApp:type_name -> cedar_policy_core.Expr.UnaryApp
	34, // 33: cedar_policy_core.Expr.bApp:type_name -> cedar_policy_core.Expr.BinaryApp
	35, // 34: cedar_policy_core.Expr.extApp:type_name -> cedar_policy_core.Expr.ExtensionFunctionApp
	36, // 35: cedar_policy_core.Expr.getAttr:type_name -> cedar_policy_core.Expr.GetAttr
	37, // 36: cedar_policy_core.Expr.hasAttr:type_name -> cedar_policy_core.Expr.HasAttr
	38, // 37: cedar_policy_core.Expr.like:type_name -> cedar_policy_core.Expr.Like
	39, // 38: cedar_policy_core.Expr.is:type_name -> cedar_policy_core.Expr.Is
	40, // 39: cedar_policy_core.Expr.set:type_name -> cedar_policy_core.Expr.Set
	41, // 40: cedar_policy_core.Expr.record:type_name -> cedar_policy_core.Expr.Record
	12, // 41: cedar_policy_core.Entity.uid:type_name -> cedar_policy_core.EntityUid
	44, // 42: cedar_policy_core.Entity.attrs:type_name -> cedar_policy_core.Entity.AttrsEntry
	12, // 43: cedar_policy_core.Entity.ancestors:type_name -> cedar_policy_core.EntityUid
	45, // 44: cedar_policy_core.Entity.tags:type_name -> cedar_policy_core.Entity.TagsEntry
	19, // 45: cedar_policy_core.Request.ContextEntry.value:type_name -> cedar_policy_core.Expr
	16, // 46: cedar_policy_core.PrincipalOrResourceConstraint.InMessage.er:type_name -> cedar_policy_core.EntityReference
	16, // 47: cedar_policy_core.PrincipalOrResourceConstraint.EqMessage.er:type_name -> cedar_policy_core.EntityReference
	13, // 48: cedar_policy_core.PrincipalOrResourceConstraint.IsMessage.entity_type:type_name -> cedar_policy_core.Name
	16, // 49: cedar_policy_core.PrincipalOrResourceConstraint.IsInMessage.er:type_name -> cedar_policy_core.EntityReference
	13, // 50: cedar_policy_core.PrincipalOrResourceConstraint.IsInMessage.entity_type:type_name -> cedar_policy_core.Name
	12, // 51: cedar_policy_core.ActionConstraint.InMessage.euids:type_name -> cedar_policy_core.EntityUid
	12, // 52: cedar_policy_core.ActionConstraint.EqMessage.euid:type_name -> cedar_policy_core.EntityUid
	12, // 53: cedar_policy_core.Expr.Literal.euid:type_name -> cedar_policy_core.EntityUid
	19, // 54: cedar_policy_core.Expr.If.test_expr:type_name -> cedar_policy_core.Expr
	19, // 55: cedar_policy_core.Expr.If.then_expr:type_name -> cedar_policy_core.Expr
	19, // 56: cedar_policy_core.Expr.If.else_expr:type_name -> cedar_policy_core.Expr
	19, // 57: cedar_policy_core.Expr.And.left:type_name -> cedar_policy_core.Expr
	19, // 58: cedar_policy_core.Expr.And.right:type_name -> cedar_policy_core.Expr
	19, // 59: cedar_policy_core.Expr.Or.left:type_name -> cedar_policy_core.Expr
	19, // 60: cedar_policy_core.Expr.Or.right:type_name -> cedar_policy_core.Expr
	6,  // 61: cedar_policy_core.Expr.UnaryApp.op:type_name -> cedar_policy_core.Expr.UnaryApp.Op
	19, // 62: cedar_policy_core.Expr.UnaryApp.expr:type_name -> cedar_policy_core.Expr
	7,  // 63: cedar_policy_core.Expr.BinaryApp.op:type_name -> cedar_policy_core.Expr.BinaryApp.Op
	19, // 64: cedar_policy_core.Expr.BinaryApp.left:type_name -> cedar_policy_core.Expr
	19, // 65: cedar_policy_core.Expr.BinaryApp.right:type_name -> cedar_policy_core.Expr
	13, // 66: cedar_policy_core.Expr.ExtensionFunctionApp.fn_name:type_name -> cedar_policy_core.Name
	19, // 67: cedar_policy_core.Expr.ExtensionFunctionApp.args:type_name -> cedar_policy_core.Expr
	19, // 68: cedar_policy_core.Expr.GetAttr.expr:type_name -> cedar_policy_core.Expr
	19, // 69: cedar_policy_core.Expr.HasAttr.expr:type_name -> cedar_policy_core.Expr
	19, // 70: cedar_policy_core.Expr.Like.expr:type_name -> cedar_policy_core.Expr
	42, // 71: cedar_policy_core.Expr.Like.pattern:type_name -> cedar_policy_core.Expr.Like.PatternElem
	19, // 72: cedar_policy_core.Expr.Is.expr:type_name -> cedar_policy_core.Expr
	13, // 73: cedar_policy_core.Expr.Is.entity_type:type_name -> cedar_policy_core.Name
	19, // 74: cedar_policy_core.Expr.Set.elements:type_name -> cedar_policy_core.Expr
	43, // 75: cedar_policy_core.Expr.Record.items:type_name -> cedar_policy_core.Expr.Record.ItemsEntry
	8,  // 76: cedar_policy_core.Expr.Like.PatternElem.wildcard:type_name -> cedar_policy_core.Expr.Like.PatternElem.Wildcard
	19, // 77: cedar_policy_core.Expr.Record.ItemsEntry.value:type_name -> cedar_policy_core.Expr
	19, // 78: cedar_policy_core.Entity.AttrsEntry.value:type_name -> cedar_policy_core.Expr
	19, // 79: cedar_policy_core.Entity.TagsEntry.value:type_name -> cedar_policy_core.Expr
	80, // [80:80] is the sub-list for method output_type
	80, // [80:80] is the sub-list for method input_type
	80, // [80:80] is the sub-list for extension type_name
	80, // [80:80] is the sub-list for extension extendee
	0,  // [0:80] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_core_proto_msgTypes[5].OneofWrappers = []any{}
	file_core_proto_msgTypes[7].OneofWrappers = []any{
		(*EntityReference_Slot_)(nil),
		(*EntityReference_Euid)(nil),
	}
	file_core_proto_msgTypes[8].OneofWrappers = []any{
		(*PrincipalOrResourceConstraint_Any_)(nil),
		(*PrincipalOrResourceConstraint_In)(nil),
		(*PrincipalOrResourceConstraint_Eq)(nil),
		(*PrincipalOrResourceConstraint_Is)(nil),
		(*PrincipalOrResourceConstraint_IsIn)(nil),
	}
	file_core_proto_msgTypes[9].OneofWrappers = []any{
		(*ActionConstraint_Any_)(nil),
		(*ActionConstraint_In)(nil),
		(*ActionConstraint_Eq)(nil),
	}
	file_core_proto_msgTypes[10].OneofWrappers = []any{
		(*Expr_Lit)(nil),
		(*Expr_Var_)(nil),
		(*Expr_Slot)(nil),
		(*Expr_If_)(nil),
		(*Expr_And_)(nil),
		(*Expr_Or_)(nil),
		(*Expr_UApp)(nil),
		(*Expr_BApp)(nil),
		(*Expr_ExtApp)(nil),
		(*Expr_GetAttr_)(nil),
		(*Expr_HasAttr_)(nil),
		(*Expr_Like_)(nil),
		(*Expr_Is_)(nil),
		(*Expr_Set_)(nil),
		(*Expr_Record_)(nil),
	}
	file_core_proto_msgTypes[20].OneofWrappers = []any{
		(*Expr_Literal_B)(nil),
		(*Expr_Literal_I)(nil),
		(*Expr_Literal_S)(nil),
		(*Expr_Literal_Euid)(nil),
	}
	file_core_proto_msgTypes[33].OneofWrappers = []any{
		(*Expr_Like_PatternElem_Wildcard_)(nil),
		(*Expr_Like_PatternElem_C)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		EnumInfos:         file_core_proto_enumTypes,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
